// ---------------------------------------------------------------------------------------------------------------------
// Imports
// ---------------------------------------------------------------------------------------------------------------------
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Immutable;
using System.Text;

namespace TUnit.Assertions.SourceGenerator;

// ---------------------------------------------------------------------------------------------------------------------
// Code
// ---------------------------------------------------------------------------------------------------------------------
[Generator(LanguageNames.CSharp)]
public class GenerateAssertionsGenerator : IIncrementalGenerator  {
    public void Initialize(IncrementalGeneratorInitializationContext context) {
        IncrementalValueProvider<ImmutableArray<GenerateAssertionDto>> data = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: (s, _) => s is ClassDeclarationSyntax,
                GenerateAssertionDtoFactory.Create)
            .Where(dto => dto is not null && !dto.IsEmpty)
            .Collect()!;
        
        context.RegisterSourceOutput(context.CompilationProvider.Combine(data), 
            static (SourceProductionContext spc, (Compilation Compilation, ImmutableArray<GenerateAssertionDto> DtoArray) box) => {
                Compilation compilation = box.Compilation;
                ImmutableArray<GenerateAssertionDto> dtoArray = box.DtoArray;
                var builder = new StringBuilder();

                foreach (GenerateAssertionDto dto in dtoArray) {
                    builder.AppendLine("// <auto-generated/>");
                    builder.AppendLine($"namespace {dto.Namespace}");
                    builder.AppendLine("{");
                    builder.AppendLine($"    public partial class {dto.ClassName}");
                    builder.AppendLine("    {");
            
                    // Generate Is assertions
                    foreach (AttributeData isAssertion in dto.IsAssertions)
                    {
                        string? methodName = isAssertion.ConstructorArguments[0].Value?.ToString();
                        if (string.IsNullOrEmpty(methodName)) continue;
                
                        builder.AppendLine($"        public void {methodName}()");
                        builder.AppendLine("        {");
                        // TODO Assertion Logic
                        builder.AppendLine("        }");
                    }
                    // Generate IsNot assertions
                    foreach (AttributeData isNotAssertion in dto.IsNotAssertions)
                    {
                        string? methodName = isNotAssertion.ConstructorArguments[0].Value?.ToString();
                        if (string.IsNullOrEmpty(methodName)) continue;
                
                        builder.AppendLine($"        public void {methodName}()");
                        builder.AppendLine("        {");
                        // TODO Assertion Logic
                        builder.AppendLine("        }");
                    }
            
                    builder.AppendLine("    }");
                    builder.AppendLine("}");
            
                    // spc.AddSource($"GenerateAssertionsGenerator.{dto.Namespace}.{dto.ClassName}.g.cs", builder.ToString());
                    spc.AddSource($"{dto.Namespace}.{dto.ClassName}.g.cs", builder.ToString());
                    builder.Clear();
                }
            });

    }
}
