using System.ComponentModel;
using System.Runtime.CompilerServices;
using TUnit.Assertions.Conditions;
using TUnit.Assertions.Core;
using TUnit.Assertions.Should.Attributes;
using TUnit.Assertions.Sources;

namespace TUnit.Assertions.Should.Core;

/// <summary>
/// Should-flavored entry wrapper for collections. Mirrors
/// <see cref="CollectionAssertionBase{TCollection, TItem}"/>'s instance-method approach so
/// element-typed assertions like <c>BeInOrder</c>/<c>All</c>/<c>HaveSingleItem</c> work
/// without explicit type arguments — the generated extension form
/// <c>Method&lt;TCollection, TItem&gt;(IShouldSource&lt;TCollection&gt;)</c> can't infer <c>TItem</c>
/// from a constraint alone.
/// <para>
/// The Should-flavored instance methods (<c>BeInOrder</c>, <c>All</c>, etc.) are emitted by the
/// source generator from <see cref="CollectionAssertion{TItem}"/>'s public instance methods —
/// see <see cref="ShouldGeneratePartialAttribute"/>.
/// </para>
/// </summary>
[ShouldGeneratePartial]
public sealed partial class ShouldCollectionSource<TItem> : IShouldSource<IEnumerable<TItem>>
{
    private readonly CollectionAssertion<TItem> _inner;

    public AssertionContext<IEnumerable<TItem>> Context { get; }

    [EditorBrowsable(EditorBrowsableState.Never)]
    public ShouldCollectionSource(IEnumerable<TItem>? value, string? expression)
    {
        _inner = new CollectionAssertion<TItem>(value!, expression);
        Context = ((IAssertionSource<IEnumerable<TItem>>)_inner).Context;
        // CollectionAssertion seeds the ExpressionBuilder with "Assert.That({expression})" — replace
        // it with the Should-flavored "{expression}.Should()" so failure messages match the entry form.
        Context.ExpressionBuilder.Clear();
        Context.ExpressionBuilder.Append(expression ?? "?").Append(".Should()");
    }

    // The next three methods can't be source-generated by the simple-factory rule: their target
    // assertion ctors take a separate `predicateDescription` string (e.g.
    // CollectionAllAssertion(ctx, predicate, predicateDescription)) which the source-side method
    // fills from the CAE expression value with a literal fallback — a one-method-param-to-two-
    // ctor-params shape the generator's filter rejects.

    public ShouldAssertion<IEnumerable<TItem>> All(
        Func<TItem, bool> predicate,
        [CallerArgumentExpression(nameof(predicate))] string? expression = null)
    {
        Context.ExpressionBuilder.Append(".All(").Append(expression).Append(')');
        var inner = new CollectionAllAssertion<IEnumerable<TItem>, TItem>(Context, predicate, expression ?? "predicate");
        return new ShouldAssertion<IEnumerable<TItem>>(Context, inner);
    }

    public ShouldAssertion<IEnumerable<TItem>> Any(
        Func<TItem, bool> predicate,
        [CallerArgumentExpression(nameof(predicate))] string? expression = null)
    {
        Context.ExpressionBuilder.Append(".Any(").Append(expression).Append(')');
        var inner = new CollectionAnyAssertion<IEnumerable<TItem>, TItem>(Context, predicate, expression ?? "predicate");
        return new ShouldAssertion<IEnumerable<TItem>>(Context, inner);
    }

    public ShouldAssertion<IEnumerable<TItem>> HaveSingleItem(
        Func<TItem, bool> predicate,
        [CallerArgumentExpression(nameof(predicate))] string? expression = null)
    {
        Context.ExpressionBuilder.Append(".HaveSingleItem(").Append(expression).Append(')');
        var inner = new HasSingleItemPredicateAssertion<IEnumerable<TItem>, TItem>(Context, predicate, expression ?? "predicate");
        return new ShouldAssertion<IEnumerable<TItem>>(Context, inner);
    }
}
