using System.ComponentModel;
using System.Runtime.CompilerServices;
using System.Text;
using TUnit.Assertions.Conditions;
using TUnit.Assertions.Core;
using TUnit.Assertions.Should.Attributes;
using TUnit.Assertions.Sources;

namespace TUnit.Assertions.Should.Core;

/// <summary>
/// Should-flavored entry wrapper for collections. Exposes element-typed instance methods
/// (<c>BeInOrder</c>/<c>All</c>/<c>HaveSingleItem</c>) so callers don't need explicit type
/// arguments — the generated extension form
/// <c>Method&lt;TCollection, TItem&gt;(IShouldSource&lt;TCollection&gt;)</c> can't infer
/// <c>TItem</c> from a constraint alone.
/// <para>
/// The Should-flavored instance methods are emitted by the source generator from
/// <see cref="CollectionAssertion{TItem}"/>'s public instance methods — see
/// <see cref="ShouldGeneratePartialAttribute{T}"/>.
/// </para>
/// </summary>
[ShouldGeneratePartial(typeof(CollectionAssertion<>))]
public sealed partial class ShouldCollectionSource<TItem> : IShouldSource<IEnumerable<TItem>>
{
    public AssertionContext<IEnumerable<TItem>> Context { get; }

    [EditorBrowsable(EditorBrowsableState.Never)]
    public ShouldCollectionSource(IEnumerable<TItem>? value, string? expression)
    {
        var sb = new StringBuilder((expression?.Length ?? 1) + 16);
        sb.Append(expression ?? "?").Append(".Should()");
        Context = new AssertionContext<IEnumerable<TItem>>(value, sb);
    }

    // The next three methods can't be source-generated by the simple-factory rule: their target
    // assertion ctors take a separate `predicateDescription` string (e.g.
    // CollectionAllAssertion(ctx, predicate, predicateDescription)) which the source-side method
    // fills from the CAE expression value with a literal fallback — a one-method-param-to-two-
    // ctor-params shape the generator's filter rejects.

    public ShouldAssertion<IEnumerable<TItem>> All(
        Func<TItem, bool> predicate,
        [CallerArgumentExpression(nameof(predicate))] string? expression = null)
    {
        Context.ExpressionBuilder.Append(".All(").Append(expression).Append(')');
        var inner = new CollectionAllAssertion<IEnumerable<TItem>, TItem>(Context, predicate, expression ?? "predicate");
        return new ShouldAssertion<IEnumerable<TItem>>(Context, inner);
    }

    public ShouldAssertion<IEnumerable<TItem>> Any(
        Func<TItem, bool> predicate,
        [CallerArgumentExpression(nameof(predicate))] string? expression = null)
    {
        Context.ExpressionBuilder.Append(".Any(").Append(expression).Append(')');
        var inner = new CollectionAnyAssertion<IEnumerable<TItem>, TItem>(Context, predicate, expression ?? "predicate");
        return new ShouldAssertion<IEnumerable<TItem>>(Context, inner);
    }

    public ShouldAssertion<IEnumerable<TItem>> HaveSingleItem(
        Func<TItem, bool> predicate,
        [CallerArgumentExpression(nameof(predicate))] string? expression = null)
    {
        Context.ExpressionBuilder.Append(".HaveSingleItem(").Append(expression).Append(')');
        var inner = new HasSingleItemPredicateAssertion<IEnumerable<TItem>, TItem>(Context, predicate, expression ?? "predicate");
        return new ShouldAssertion<IEnumerable<TItem>>(Context, inner);
    }
}
