using System.Collections.Immutable;
using Microsoft.CodeAnalysis;
using TUnit.Mocks.SourceGenerator.Builders;
using TUnit.Mocks.SourceGenerator.Discovery;
using TUnit.Mocks.SourceGenerator.Models;

namespace TUnit.Mocks.SourceGenerator;

[Generator(LanguageNames.CSharp)]
public class MockGenerator : IIncrementalGenerator
{
    private readonly Action<MockSourceSink, MockTypeModel> _emitSources;

    public MockGenerator() : this(EmitSources)
    {
    }

    internal MockGenerator(Action<MockSourceSink, MockTypeModel> emitSources)
    {
        _emitSources = emitSources;
    }

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Always emit the TUnit.Mocks.Generated namespace so that global usings never fail
        context.RegisterPostInitializationOutput(ctx =>
        {
            ctx.AddSource("TUnit.Mocks.Generated.Namespace.g.cs", """
                // <auto-generated/>
                #pragma warning disable
                #nullable enable

                namespace TUnit.Mocks.Generated;
                """);
        });

        // Step 1a: Find all Mock.Of<T>() invocations and transform to model arrays
        var mockTypes = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: MockTypeDiscovery.IsMockOfInvocation,
                transform: static (ctx, ct) => CreateRequests(
                    MockTypeDiscovery.TransformToModels(ctx, ct),
                    ctx.Node.GetLocation()))
            .WithTrackingName(MockTrackingNames.MockOfInvocations)
            .SelectMany((requests, _) => requests.AsImmutableArray());

        // Step 1b: Find all [assembly: GenerateMock(typeof(T))] attributes
        var attributeTypes = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                "TUnit.Mocks.GenerateMockAttribute",
                predicate: static (node, _) => true,
                transform: MockTypeDiscovery.TransformGenerateMockAttribute)
            .WithTrackingName(MockTrackingNames.GenerateMockAttributes)
            .SelectMany((requests, _) => requests.AsImmutableArray());

        // Attribute-only requests have no invocation for the TM006 analyzer to inspect.
        context.RegisterSourceOutput(attributeTypes, static (spc, request) =>
        {
            if (!request.Model.LacksAccessibleConstructor)
            {
                return;
            }

            spc.ReportDiagnostic(Diagnostic.Create(
                Diagnostics.TM006_CannotMockTypeWithoutAccessibleConstructor,
                request.SourceLocation.ToLocation(),
                request.Model.FullyQualifiedName));
        });

        // Step 1c: Find all IFoo.Mock() static extension invocations
        var extensionTypes = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: MockTypeDiscovery.IsMockExtensionInvocation,
                transform: static (ctx, ct) => CreateRequests(
                    MockTypeDiscovery.TransformMockExtensionInvocation(ctx, ct),
                    ctx.Node.GetLocation()))
            .WithTrackingName(MockTrackingNames.MockExtensionInvocations)
            .SelectMany((requests, _) => requests.AsImmutableArray());

        // Step 2: Merge all sources and deduplicate
        var distinctRequests = mockTypes
            .Collect()
            .Combine(attributeTypes.Collect())
            .Combine(extensionTypes.Collect())
            .SelectMany((pair, _) =>
            {
                var (mockOfAndAttribute, extensionInvocations) = pair;
                var (mockOfRequests, attributeRequests) = mockOfAndAttribute;
                var set = new HashSet<MockTypeModel>();
                var requests = new List<MockGenerationRequest>();

                AddDistinctRequests(mockOfRequests, set, requests);
                AddDistinctRequests(attributeRequests, set, requests);
                AddDistinctRequests(extensionInvocations, set, requests);

                // Flag types that would emit the same generated names before anything is written:
                // duplicate hint names abort the generator and take every mock in the compilation
                // with them. See issue #6505. One target mocked in several modes is not such a
                // collision — it just has to agree on who emits the shared member surface (#6834).
                return SharedMemberSurfaceResolver.Resolve(
                    GeneratedNameCollisionDetector.Annotate(requests));
            })
            .WithTrackingName(MockTrackingNames.DistinctRequests);

        // Step 3: Generate source for each unique type. The request's location is dropped first,
        // so a call site that merely moves (an edit above it) leaves the model — and with it the
        // generated source — cached.
        var emitResults = distinctRequests
            .Select(static (request, _) => request.Model)
            .WithTrackingName(MockTrackingNames.DistinctModels)
            .Select((model, _) => Emit(model))
            .WithTrackingName(MockTrackingNames.EmitResults);

        context.RegisterSourceOutput(emitResults, AddEmittedSources);

        // Step 4: TM009 needs the location of the request that produced a failed model. Pairing
        // happens here rather than in the emit step so locations never invalidate emitted source.
        var failures = emitResults
            .Where(static result => result.Failed)
            .Collect()
            .Combine(distinctRequests.Collect());

        context.RegisterSourceOutput(failures, ReportGenerationFailures);
    }

    private MockEmitResult Emit(MockTypeModel model)
    {
        var sink = new MockSourceSink();

        try
        {
            _emitSources(sink, model);
            return new MockEmitResult(model, sink.ToEquatableArray(), null, null);
        }
        catch (Exception exception) when (exception is not OperationCanceledException)
        {
            // Sources added before the failure are still emitted, as they were when generation
            // wrote straight to the SourceProductionContext.
            return new MockEmitResult(model, sink.ToEquatableArray(), exception.GetType().Name, exception.Message);
        }
    }

    private static void AddEmittedSources(SourceProductionContext spc, MockEmitResult result)
    {
        var model = result.Model;
        if (model.CollidesWith is not null)
        {
            spc.ReportDiagnostic(Diagnostic.Create(
                Diagnostics.TM008_GeneratedNameCollision,
                Location.None,
                model.FullyQualifiedName,
                MockImplBuilder.GetCompositeSafeName(model),
                model.CollidesWith));
        }

        foreach (var source in result.Sources)
        {
            spc.AddSource(source.HintName, source.Source);
        }
    }

    private static void ReportGenerationFailures(
        SourceProductionContext spc,
        (ImmutableArray<MockEmitResult> Failures, ImmutableArray<MockGenerationRequest> Requests) input)
    {
        foreach (var failure in input.Failures)
        {
            var location = Location.None;
            foreach (var request in input.Requests)
            {
                if (request.Model.Equals(failure.Model))
                {
                    location = request.SourceLocation.ToLocation();
                    break;
                }
            }

            spc.ReportDiagnostic(Diagnostic.Create(
                Diagnostics.TM009_GenerationFailed,
                location,
                failure.Model.FullyQualifiedName,
                failure.FailureExceptionType,
                failure.FailureMessage));
        }
    }

    private static EquatableArray<MockGenerationRequest> CreateRequests(
        ImmutableArray<MockTypeModel> models,
        Location location)
    {
        if (models.IsDefaultOrEmpty)
        {
            return EquatableArray<MockGenerationRequest>.Empty;
        }

        var sourceLocation = MockSourceLocation.From(location);
        var requests = ImmutableArray.CreateBuilder<MockGenerationRequest>(models.Length);
        foreach (var model in models)
        {
            requests.Add(new MockGenerationRequest(model, sourceLocation));
        }

        return new EquatableArray<MockGenerationRequest>(requests.MoveToImmutable());
    }

    private static void AddDistinctRequests(
        ImmutableArray<MockGenerationRequest> requests,
        HashSet<MockTypeModel> set,
        List<MockGenerationRequest> distinctRequests)
    {
        foreach (var request in requests)
        {
            if (!set.Add(request.Model))
            {
                continue;
            }

            distinctRequests.Add(request);
        }
    }

    internal static void EmitSources(MockSourceSink spc, MockTypeModel model)
    {
        if (model.CollidesWith is not null)
        {
            // TM008 is reported when the (empty) result is added to the compilation.
            return;
        }

        if (model.IsSecondaryMemberSurface)
        {
            // Pair model: the shared setup/verify surface for one additional interface of a
            // multi-type mock. Emitted once per (primary, interface) pair across all combos.
            var secondaryMembersSource = MockMembersBuilder.Build(model);
            spc.AddSource($"{GetSafeFileName(model)}_MockSecondaryMembers.g.cs", secondaryMembersSource);
        }
        else if (model.IsDelegateType)
        {
            // Delegate mock: generate members and delegate factory (no impl class)
            GenerateDelegateMock(spc, model);
        }
        else if (model.LacksAccessibleConstructor)
        {
            // Unsubclassable class (every constructor private / cross-assembly internal).
            // Emit only the static Mock() entry point so the call site still binds and the
            // TM006 analyzer diagnostic is the single error the user sees, instead of a
            // CS1729 pointing into generated code. See issue #6493.
            GenerateUnconstructableClassStub(spc, model);
        }
        else if (model.IsWrapMock)
        {
            // Wrap mock: generate wrap impl, wrap factory, plus members
            GenerateWrapMock(spc, model);
        }
        else if (model.AdditionalInterfaceNames.Length > 0)
        {
            // Multi-interface mock: generate impl + factory + secondary-member setup
            // extensions. Primary members/raise come from the single-type model (also emitted).
            GenerateMultiInterfaceMock(spc, model);
        }
        else
        {
            // Single-type mock: generate everything
            GenerateSingleTypeMock(spc, model);
        }
    }

    private static void GenerateSingleTypeMock(MockSourceSink spc, MockTypeModel model)
    {
        var fileName = GetSafeFileName(model);

        // Defence-in-depth: MemberDiscovery never sets HasStaticAbstractMembers for class targets
        // (TypeKind guard in TryCollectStaticAbstractFromInterface), so this branch is only entered
        // for interface targets. The IsInterface check makes the intent explicit.
        if (model.HasStaticAbstractMembers && model.IsInterface)
        {
            var bridgeSource = MockBridgeBuilder.Build(model);
            spc.AddSource($"{fileName}_MockBridge.g.cs", bridgeSource);
        }

        GenerateImplFactoryMembersAndEvents(spc, model, fileName);

        if (model.IsInterface)
        {
            var wrapperSource = MockWrapperTypeBuilder.Build(model);
            if (!string.IsNullOrEmpty(wrapperSource))
            {
                spc.AddSource($"{fileName}_Mock.g.cs", wrapperSource);
            }

            var extensionSource = MockStaticExtensionBuilder.Build(model);
            if (!string.IsNullOrEmpty(extensionSource))
            {
                spc.AddSource($"{fileName}_MockStaticExtension.g.cs", extensionSource);
            }
        }
        else if (model.IsPartialMock)
        {
            var extensionSource = MockStaticExtensionBuilder.BuildForPartialMock(model);
            if (!string.IsNullOrEmpty(extensionSource))
            {
                spc.AddSource($"{fileName}_MockStaticExtension.g.cs", extensionSource);
            }
        }
    }

    private static void GenerateUnconstructableClassStub(MockSourceSink spc, MockTypeModel model)
    {
        var extensionSource = MockStaticExtensionBuilder.BuildForPartialMock(model);
        if (!string.IsNullOrEmpty(extensionSource))
        {
            spc.AddSource($"{GetSafeFileName(model)}_MockStaticExtension.g.cs", extensionSource);
        }
    }

    private static void GenerateDelegateMock(MockSourceSink spc, MockTypeModel model)
    {
        var fileName = GetSafeFileName(model);

        var membersSource = MockMembersBuilder.Build(model);
        spc.AddSource($"{fileName}_MockMembers.g.cs", membersSource);

        var factorySource = MockDelegateFactoryBuilder.Build(model);
        spc.AddSource($"{fileName}_MockDelegateFactory.g.cs", factorySource);
    }

    private static void GenerateWrapMock(MockSourceSink spc, MockTypeModel model)
    {
        var fileName = GetSafeFileName(model);

        // The wrap impl and factory are already types of their own (file-scoped `{name}WrapMockImpl`
        // and `{name}WrapMockFactory`), so a hint name of their own is all they need to coexist with
        // the regular mock of the same type (#6834).
        spc.AddSource($"{fileName}_WrapMockImplFactory.g.cs", BuildCombinedImplAndFactory(model));

        // The member surface belongs to the type rather than to the mode, so the regular model
        // emits it whenever the type is also mocked that way.
        if (model.EmitsSharedMemberSurface)
        {
            GenerateMembersAndEvents(spc, model, fileName);
        }
    }

    private static void GenerateMultiInterfaceMock(MockSourceSink spc, MockTypeModel model)
    {
        var fileName = GetSafeFileName(model);
        var implFactorySource = BuildCombinedImplAndFactory(model);
        spc.AddSource($"{fileName}_MockImplFactory.g.cs", implFactorySource);
    }

    private static void GenerateImplFactoryMembersAndEvents(MockSourceSink spc, MockTypeModel model, string fileName)
    {
        var implFactorySource = BuildCombinedImplAndFactory(model);
        spc.AddSource($"{fileName}_MockImplFactory.g.cs", implFactorySource);

        GenerateMembersAndEvents(spc, model, fileName);
    }

    private static void GenerateMembersAndEvents(MockSourceSink spc, MockTypeModel model, string fileName)
    {
        var membersSource = MockMembersBuilder.Build(model);
        spc.AddSource($"{fileName}_MockMembers.g.cs", membersSource);

        if (model.Events.Length > 0)
        {
            var eventsSource = MockEventsBuilder.Build(model);
            spc.AddSource($"{fileName}_MockEvents.g.cs", eventsSource);
        }
    }

    private static string BuildCombinedImplAndFactory(MockTypeModel model)
    {
        var writer = new CodeWriter();
        var mockNamespace = MockImplBuilder.GetMockNamespace(model);

        writer.AppendLine("// <auto-generated/>");
        writer.AppendLine("#pragma warning disable");
        writer.AppendLine("#nullable enable");
        writer.AppendLine();

        using (writer.OptionalNamespaceBlock(mockNamespace))
        {
            MockImplBuilder.BuildInto(writer, model);
            writer.AppendLine();
            MockFactoryBuilder.BuildInto(writer, model);
        }

        return writer.ToString();
    }

    private static string GetSafeFileName(MockTypeModel model)
        => MockImplBuilder.GetCompositeSafeName(model);
}
