using System.Threading.Tasks;

namespace UnifiedTests;

#if MSTEST
[TestClass]
#elif NUNIT
[TestFixture]
#endif
public class ScaleTests
{
#if TUNIT
    [Test]
    [Arguments(0)]
    [Arguments(1)]
    [Arguments(2)]
    [Arguments(3)]
    [Arguments(4)]
    [Arguments(5)]
    [Arguments(6)]
    [Arguments(7)]
    [Arguments(8)]
    [Arguments(9)]
    [Arguments(10)]
    [Arguments(11)]
    [Arguments(12)]
    [Arguments(13)]
    [Arguments(14)]
    [Arguments(15)]
    [Arguments(16)]
    [Arguments(17)]
    [Arguments(18)]
    [Arguments(19)]
    [Arguments(20)]
    [Arguments(21)]
    [Arguments(22)]
    [Arguments(23)]
    [Arguments(24)]
    [Arguments(25)]
    [Arguments(26)]
    [Arguments(27)]
    [Arguments(28)]
    [Arguments(29)]
    [Arguments(30)]
    [Arguments(31)]
    [Arguments(32)]
    [Arguments(33)]
    [Arguments(34)]
    [Arguments(35)]
    [Arguments(36)]
    [Arguments(37)]
    [Arguments(38)]
    [Arguments(39)]
    [Arguments(40)]
    [Arguments(41)]
    [Arguments(42)]
    [Arguments(43)]
    [Arguments(44)]
    [Arguments(45)]
    [Arguments(46)]
    [Arguments(47)]
    [Arguments(48)]
    [Arguments(49)]
    [Arguments(50)]
    [Arguments(51)]
    [Arguments(52)]
    [Arguments(53)]
    [Arguments(54)]
    [Arguments(55)]
    [Arguments(56)]
    [Arguments(57)]
    [Arguments(58)]
    [Arguments(59)]
    [Arguments(60)]
    [Arguments(61)]
    [Arguments(62)]
    [Arguments(63)]
    [Arguments(64)]
    [Arguments(65)]
    [Arguments(66)]
    [Arguments(67)]
    [Arguments(68)]
    [Arguments(69)]
    [Arguments(70)]
    [Arguments(71)]
    [Arguments(72)]
    [Arguments(73)]
    [Arguments(74)]
    [Arguments(75)]
    [Arguments(76)]
    [Arguments(77)]
    [Arguments(78)]
    [Arguments(79)]
    [Arguments(80)]
    [Arguments(81)]
    [Arguments(82)]
    [Arguments(83)]
    [Arguments(84)]
    [Arguments(85)]
    [Arguments(86)]
    [Arguments(87)]
    [Arguments(88)]
    [Arguments(89)]
    [Arguments(90)]
    [Arguments(91)]
    [Arguments(92)]
    [Arguments(93)]
    [Arguments(94)]
    [Arguments(95)]
    [Arguments(96)]
    [Arguments(97)]
    [Arguments(98)]
    [Arguments(99)]
    public void Scale100_ParameterizedTest(int value)
#elif XUNIT || XUNIT3
    [Theory]
    [InlineData(0)]
    [InlineData(1)]
    [InlineData(2)]
    [InlineData(3)]
    [InlineData(4)]
    [InlineData(5)]
    [InlineData(6)]
    [InlineData(7)]
    [InlineData(8)]
    [InlineData(9)]
    [InlineData(10)]
    [InlineData(11)]
    [InlineData(12)]
    [InlineData(13)]
    [InlineData(14)]
    [InlineData(15)]
    [InlineData(16)]
    [InlineData(17)]
    [InlineData(18)]
    [InlineData(19)]
    [InlineData(20)]
    [InlineData(21)]
    [InlineData(22)]
    [InlineData(23)]
    [InlineData(24)]
    [InlineData(25)]
    [InlineData(26)]
    [InlineData(27)]
    [InlineData(28)]
    [InlineData(29)]
    [InlineData(30)]
    [InlineData(31)]
    [InlineData(32)]
    [InlineData(33)]
    [InlineData(34)]
    [InlineData(35)]
    [InlineData(36)]
    [InlineData(37)]
    [InlineData(38)]
    [InlineData(39)]
    [InlineData(40)]
    [InlineData(41)]
    [InlineData(42)]
    [InlineData(43)]
    [InlineData(44)]
    [InlineData(45)]
    [InlineData(46)]
    [InlineData(47)]
    [InlineData(48)]
    [InlineData(49)]
    [InlineData(50)]
    [InlineData(51)]
    [InlineData(52)]
    [InlineData(53)]
    [InlineData(54)]
    [InlineData(55)]
    [InlineData(56)]
    [InlineData(57)]
    [InlineData(58)]
    [InlineData(59)]
    [InlineData(60)]
    [InlineData(61)]
    [InlineData(62)]
    [InlineData(63)]
    [InlineData(64)]
    [InlineData(65)]
    [InlineData(66)]
    [InlineData(67)]
    [InlineData(68)]
    [InlineData(69)]
    [InlineData(70)]
    [InlineData(71)]
    [InlineData(72)]
    [InlineData(73)]
    [InlineData(74)]
    [InlineData(75)]
    [InlineData(76)]
    [InlineData(77)]
    [InlineData(78)]
    [InlineData(79)]
    [InlineData(80)]
    [InlineData(81)]
    [InlineData(82)]
    [InlineData(83)]
    [InlineData(84)]
    [InlineData(85)]
    [InlineData(86)]
    [InlineData(87)]
    [InlineData(88)]
    [InlineData(89)]
    [InlineData(90)]
    [InlineData(91)]
    [InlineData(92)]
    [InlineData(93)]
    [InlineData(94)]
    [InlineData(95)]
    [InlineData(96)]
    [InlineData(97)]
    [InlineData(98)]
    [InlineData(99)]
    public void Scale100_ParameterizedTest(int value)
#elif NUNIT
    [TestCase(0)]
    [TestCase(1)]
    [TestCase(2)]
    [TestCase(3)]
    [TestCase(4)]
    [TestCase(5)]
    [TestCase(6)]
    [TestCase(7)]
    [TestCase(8)]
    [TestCase(9)]
    [TestCase(10)]
    [TestCase(11)]
    [TestCase(12)]
    [TestCase(13)]
    [TestCase(14)]
    [TestCase(15)]
    [TestCase(16)]
    [TestCase(17)]
    [TestCase(18)]
    [TestCase(19)]
    [TestCase(20)]
    [TestCase(21)]
    [TestCase(22)]
    [TestCase(23)]
    [TestCase(24)]
    [TestCase(25)]
    [TestCase(26)]
    [TestCase(27)]
    [TestCase(28)]
    [TestCase(29)]
    [TestCase(30)]
    [TestCase(31)]
    [TestCase(32)]
    [TestCase(33)]
    [TestCase(34)]
    [TestCase(35)]
    [TestCase(36)]
    [TestCase(37)]
    [TestCase(38)]
    [TestCase(39)]
    [TestCase(40)]
    [TestCase(41)]
    [TestCase(42)]
    [TestCase(43)]
    [TestCase(44)]
    [TestCase(45)]
    [TestCase(46)]
    [TestCase(47)]
    [TestCase(48)]
    [TestCase(49)]
    [TestCase(50)]
    [TestCase(51)]
    [TestCase(52)]
    [TestCase(53)]
    [TestCase(54)]
    [TestCase(55)]
    [TestCase(56)]
    [TestCase(57)]
    [TestCase(58)]
    [TestCase(59)]
    [TestCase(60)]
    [TestCase(61)]
    [TestCase(62)]
    [TestCase(63)]
    [TestCase(64)]
    [TestCase(65)]
    [TestCase(66)]
    [TestCase(67)]
    [TestCase(68)]
    [TestCase(69)]
    [TestCase(70)]
    [TestCase(71)]
    [TestCase(72)]
    [TestCase(73)]
    [TestCase(74)]
    [TestCase(75)]
    [TestCase(76)]
    [TestCase(77)]
    [TestCase(78)]
    [TestCase(79)]
    [TestCase(80)]
    [TestCase(81)]
    [TestCase(82)]
    [TestCase(83)]
    [TestCase(84)]
    [TestCase(85)]
    [TestCase(86)]
    [TestCase(87)]
    [TestCase(88)]
    [TestCase(89)]
    [TestCase(90)]
    [TestCase(91)]
    [TestCase(92)]
    [TestCase(93)]
    [TestCase(94)]
    [TestCase(95)]
    [TestCase(96)]
    [TestCase(97)]
    [TestCase(98)]
    [TestCase(99)]
    public void Scale100_ParameterizedTest(int value)
#elif MSTEST
    [TestMethod]
    [DataRow(0)]
    [DataRow(1)]
    [DataRow(2)]
    [DataRow(3)]
    [DataRow(4)]
    [DataRow(5)]
    [DataRow(6)]
    [DataRow(7)]
    [DataRow(8)]
    [DataRow(9)]
    [DataRow(10)]
    [DataRow(11)]
    [DataRow(12)]
    [DataRow(13)]
    [DataRow(14)]
    [DataRow(15)]
    [DataRow(16)]
    [DataRow(17)]
    [DataRow(18)]
    [DataRow(19)]
    [DataRow(20)]
    [DataRow(21)]
    [DataRow(22)]
    [DataRow(23)]
    [DataRow(24)]
    [DataRow(25)]
    [DataRow(26)]
    [DataRow(27)]
    [DataRow(28)]
    [DataRow(29)]
    [DataRow(30)]
    [DataRow(31)]
    [DataRow(32)]
    [DataRow(33)]
    [DataRow(34)]
    [DataRow(35)]
    [DataRow(36)]
    [DataRow(37)]
    [DataRow(38)]
    [DataRow(39)]
    [DataRow(40)]
    [DataRow(41)]
    [DataRow(42)]
    [DataRow(43)]
    [DataRow(44)]
    [DataRow(45)]
    [DataRow(46)]
    [DataRow(47)]
    [DataRow(48)]
    [DataRow(49)]
    [DataRow(50)]
    [DataRow(51)]
    [DataRow(52)]
    [DataRow(53)]
    [DataRow(54)]
    [DataRow(55)]
    [DataRow(56)]
    [DataRow(57)]
    [DataRow(58)]
    [DataRow(59)]
    [DataRow(60)]
    [DataRow(61)]
    [DataRow(62)]
    [DataRow(63)]
    [DataRow(64)]
    [DataRow(65)]
    [DataRow(66)]
    [DataRow(67)]
    [DataRow(68)]
    [DataRow(69)]
    [DataRow(70)]
    [DataRow(71)]
    [DataRow(72)]
    [DataRow(73)]
    [DataRow(74)]
    [DataRow(75)]
    [DataRow(76)]
    [DataRow(77)]
    [DataRow(78)]
    [DataRow(79)]
    [DataRow(80)]
    [DataRow(81)]
    [DataRow(82)]
    [DataRow(83)]
    [DataRow(84)]
    [DataRow(85)]
    [DataRow(86)]
    [DataRow(87)]
    [DataRow(88)]
    [DataRow(89)]
    [DataRow(90)]
    [DataRow(91)]
    [DataRow(92)]
    [DataRow(93)]
    [DataRow(94)]
    [DataRow(95)]
    [DataRow(96)]
    [DataRow(97)]
    [DataRow(98)]
    [DataRow(99)]
    public void Scale100_ParameterizedTest(int value)
#endif
    {
        // Simulate realistic computational work
        var result = PerformCalculation(value);
        var squared = result * result;
        var sum = Enumerable.Range(1, value + 1).Sum();
    }

#if TUNIT
    [Test]
    [Arguments(0, "A")]
    [Arguments(1, "B")]
    [Arguments(2, "C")]
    [Arguments(3, "D")]
    [Arguments(4, "E")]
    [Arguments(5, "F")]
    [Arguments(6, "G")]
    [Arguments(7, "H")]
    [Arguments(8, "I")]
    [Arguments(9, "J")]
    [Arguments(10, "K")]
    [Arguments(11, "L")]
    [Arguments(12, "M")]
    [Arguments(13, "N")]
    [Arguments(14, "O")]
    [Arguments(15, "P")]
    [Arguments(16, "Q")]
    [Arguments(17, "R")]
    [Arguments(18, "S")]
    [Arguments(19, "T")]
    [Arguments(20, "U")]
    [Arguments(21, "V")]
    [Arguments(22, "W")]
    [Arguments(23, "X")]
    [Arguments(24, "Y")]
    [Arguments(25, "Z")]
    [Arguments(26, "AA")]
    [Arguments(27, "AB")]
    [Arguments(28, "AC")]
    [Arguments(29, "AD")]
    [Arguments(30, "AE")]
    [Arguments(31, "AF")]
    [Arguments(32, "AG")]
    [Arguments(33, "AH")]
    [Arguments(34, "AI")]
    [Arguments(35, "AJ")]
    [Arguments(36, "AK")]
    [Arguments(37, "AL")]
    [Arguments(38, "AM")]
    [Arguments(39, "AN")]
    [Arguments(40, "AO")]
    [Arguments(41, "AP")]
    [Arguments(42, "AQ")]
    [Arguments(43, "AR")]
    [Arguments(44, "AS")]
    [Arguments(45, "AT")]
    [Arguments(46, "AU")]
    [Arguments(47, "AV")]
    [Arguments(48, "AW")]
    [Arguments(49, "AX")]
    public void Scale50_MultiParamTest(int id, string name)
#elif XUNIT || XUNIT3
    [Theory]
    [InlineData(0, "A")]
    [InlineData(1, "B")]
    [InlineData(2, "C")]
    [InlineData(3, "D")]
    [InlineData(4, "E")]
    [InlineData(5, "F")]
    [InlineData(6, "G")]
    [InlineData(7, "H")]
    [InlineData(8, "I")]
    [InlineData(9, "J")]
    [InlineData(10, "K")]
    [InlineData(11, "L")]
    [InlineData(12, "M")]
    [InlineData(13, "N")]
    [InlineData(14, "O")]
    [InlineData(15, "P")]
    [InlineData(16, "Q")]
    [InlineData(17, "R")]
    [InlineData(18, "S")]
    [InlineData(19, "T")]
    [InlineData(20, "U")]
    [InlineData(21, "V")]
    [InlineData(22, "W")]
    [InlineData(23, "X")]
    [InlineData(24, "Y")]
    [InlineData(25, "Z")]
    [InlineData(26, "AA")]
    [InlineData(27, "AB")]
    [InlineData(28, "AC")]
    [InlineData(29, "AD")]
    [InlineData(30, "AE")]
    [InlineData(31, "AF")]
    [InlineData(32, "AG")]
    [InlineData(33, "AH")]
    [InlineData(34, "AI")]
    [InlineData(35, "AJ")]
    [InlineData(36, "AK")]
    [InlineData(37, "AL")]
    [InlineData(38, "AM")]
    [InlineData(39, "AN")]
    [InlineData(40, "AO")]
    [InlineData(41, "AP")]
    [InlineData(42, "AQ")]
    [InlineData(43, "AR")]
    [InlineData(44, "AS")]
    [InlineData(45, "AT")]
    [InlineData(46, "AU")]
    [InlineData(47, "AV")]
    [InlineData(48, "AW")]
    [InlineData(49, "AX")]
    public void Scale50_MultiParamTest(int id, string name)
#elif NUNIT
    [TestCase(0, "A")]
    [TestCase(1, "B")]
    [TestCase(2, "C")]
    [TestCase(3, "D")]
    [TestCase(4, "E")]
    [TestCase(5, "F")]
    [TestCase(6, "G")]
    [TestCase(7, "H")]
    [TestCase(8, "I")]
    [TestCase(9, "J")]
    [TestCase(10, "K")]
    [TestCase(11, "L")]
    [TestCase(12, "M")]
    [TestCase(13, "N")]
    [TestCase(14, "O")]
    [TestCase(15, "P")]
    [TestCase(16, "Q")]
    [TestCase(17, "R")]
    [TestCase(18, "S")]
    [TestCase(19, "T")]
    [TestCase(20, "U")]
    [TestCase(21, "V")]
    [TestCase(22, "W")]
    [TestCase(23, "X")]
    [TestCase(24, "Y")]
    [TestCase(25, "Z")]
    [TestCase(26, "AA")]
    [TestCase(27, "AB")]
    [TestCase(28, "AC")]
    [TestCase(29, "AD")]
    [TestCase(30, "AE")]
    [TestCase(31, "AF")]
    [TestCase(32, "AG")]
    [TestCase(33, "AH")]
    [TestCase(34, "AI")]
    [TestCase(35, "AJ")]
    [TestCase(36, "AK")]
    [TestCase(37, "AL")]
    [TestCase(38, "AM")]
    [TestCase(39, "AN")]
    [TestCase(40, "AO")]
    [TestCase(41, "AP")]
    [TestCase(42, "AQ")]
    [TestCase(43, "AR")]
    [TestCase(44, "AS")]
    [TestCase(45, "AT")]
    [TestCase(46, "AU")]
    [TestCase(47, "AV")]
    [TestCase(48, "AW")]
    [TestCase(49, "AX")]
    public void Scale50_MultiParamTest(int id, string name)
#elif MSTEST
    [TestMethod]
    [DataRow(0, "A")]
    [DataRow(1, "B")]
    [DataRow(2, "C")]
    [DataRow(3, "D")]
    [DataRow(4, "E")]
    [DataRow(5, "F")]
    [DataRow(6, "G")]
    [DataRow(7, "H")]
    [DataRow(8, "I")]
    [DataRow(9, "J")]
    [DataRow(10, "K")]
    [DataRow(11, "L")]
    [DataRow(12, "M")]
    [DataRow(13, "N")]
    [DataRow(14, "O")]
    [DataRow(15, "P")]
    [DataRow(16, "Q")]
    [DataRow(17, "R")]
    [DataRow(18, "S")]
    [DataRow(19, "T")]
    [DataRow(20, "U")]
    [DataRow(21, "V")]
    [DataRow(22, "W")]
    [DataRow(23, "X")]
    [DataRow(24, "Y")]
    [DataRow(25, "Z")]
    [DataRow(26, "AA")]
    [DataRow(27, "AB")]
    [DataRow(28, "AC")]
    [DataRow(29, "AD")]
    [DataRow(30, "AE")]
    [DataRow(31, "AF")]
    [DataRow(32, "AG")]
    [DataRow(33, "AH")]
    [DataRow(34, "AI")]
    [DataRow(35, "AJ")]
    [DataRow(36, "AK")]
    [DataRow(37, "AL")]
    [DataRow(38, "AM")]
    [DataRow(39, "AN")]
    [DataRow(40, "AO")]
    [DataRow(41, "AP")]
    [DataRow(42, "AQ")]
    [DataRow(43, "AR")]
    [DataRow(44, "AS")]
    [DataRow(45, "AT")]
    [DataRow(46, "AU")]
    [DataRow(47, "AV")]
    [DataRow(48, "AW")]
    [DataRow(49, "AX")]
    public void Scale50_MultiParamTest(int id, string name)
#endif
    {
        // Process string and numeric data together
        var processed = ProcessData(id, name);
        var combined = $"{id}_{name}";
        var length = combined.Length;
    }

    private int PerformCalculation(int value)
    {
        // Simulate some CPU work
        var result = 0;
        for (var i = 0; i < 10; i++)
        {
            result += value;
        }
        return result;
    }

    private string ProcessData(int id, string name)
    {
        return $"Processed_{id}_{name}_{DateTime.UtcNow.Ticks % 1000}";
    }
}
