using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using TUnit.Core.SourceGenerator.Extensions;

namespace TUnit.Core.SourceGenerator.CodeGenerators;

[Generator]
public class DataGeneratorPropertyGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var classDataSourceClasses = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is AttributeSyntax,
                transform: GetClassesWithDataSourceProperties)
            .SelectMany(static (symbols, _) => symbols)
            .WithComparer(SymbolEqualityComparer.Default);

        context.RegisterSourceOutput(classDataSourceClasses, GeneratePropertyInitializer);
    }

    private static IEnumerable<INamedTypeSymbol> GetClassesWithDataSourceProperties(GeneratorSyntaxContext context, CancellationToken cancellationToken)
    {
        if (context.Node is not AttributeSyntax attributeSyntax)
        {
            return [];
        }

        var semanticModel = context.SemanticModel;

        if(semanticModel.GetSymbolInfo(attributeSyntax).Symbol is not IMethodSymbol attributeConstructorSymbol)
        {
            return [];
        }

        var attributeClass = attributeConstructorSymbol.ContainingType;

        if (attributeClass == null)
        {
            return [];
        }

        if (!IsDataSourceGeneratorAttribute(attributeClass, out var attributeBaseType))
        {
            return [];
        }

        if (attributeBaseType?.IsGenericType is not true)
        {
            return [];
        }

        return attributeBaseType.TypeArguments
            .Where(x => x is not ITypeParameterSymbol)
            .OfType<INamedTypeSymbol>()
            .Where(HasDataGeneratorProperties);
    }

    private static bool HasDataGeneratorProperties(ITypeSymbol type)
    {
        if (type is not INamedTypeSymbol namedTypeSymbol)
        {
            return false;
        }

        return namedTypeSymbol.GetMembers()
            .OfType<IPropertySymbol>()
            .Any(property => property.GetAttributes().Any(attr => IsDataSourceGeneratorAttribute(attr.AttributeClass, out _)));
    }

    private static bool IsDataSourceGeneratorAttribute(INamedTypeSymbol? attributeClass, out INamedTypeSymbol? attributeBaseType)
    {
        if (attributeClass == null)
        {
            attributeBaseType = null;
            return false;
        }

        foreach (var type in attributeClass.GetSelfAndBaseTypes())
        {
            if(type.Interfaces.Any(i =>
                i.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) == "global::TUnit.Core.IDataSourceGeneratorAttribute"))
            {
                attributeBaseType = type;
                return true;
            }
        }

        attributeBaseType = null;
        return false;
    }

    private void GeneratePropertyInitializer(SourceProductionContext context, INamedTypeSymbol type)
    {
        try
        {
            using var sourceBuilder = new SourceCodeWriter();

            sourceBuilder.WriteLine("// <auto-generated/>");
            sourceBuilder.WriteLine("#pragma warning disable");
            sourceBuilder.WriteLine("using global::System;");
            sourceBuilder.WriteLine("using global::System.Collections.Generic;");
            sourceBuilder.WriteLine("using global::TUnit.Core;");
            sourceBuilder.WriteLine();

            var initializerClassName = $"{type.Name}PropertyInitializer_{Guid.NewGuid():N}";

            sourceBuilder.WriteLine("namespace TUnit.SourceGenerated;");
            sourceBuilder.WriteLine();
            sourceBuilder.WriteLine("[global::System.Diagnostics.StackTraceHidden]");
            sourceBuilder.WriteLine("[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]");
            sourceBuilder.WriteLine($"file static class {initializerClassName}");
            sourceBuilder.WriteLine("{");

            // Generate the initialization method
            sourceBuilder.WriteLine("[global::System.Runtime.CompilerServices.ModuleInitializer]");
            sourceBuilder.WriteLine("public static void InitializeProperties()");
            sourceBuilder.WriteLine("{");

            RegisterProperty(type, sourceBuilder);

            sourceBuilder.WriteLine("}");
            sourceBuilder.WriteLine("}");

            context.AddSource($"PropertyInitializer_{initializerClassName}.g.cs", sourceBuilder.ToString());
        }
        catch (Exception ex)
        {
            var descriptor = new DiagnosticDescriptor(
                id: "TUNIT_PROP_001",
                title: "Error generating property initializer",
                messageFormat: "Failed to generate property initializer: {0}",
                category: "SourceGenerator",
                DiagnosticSeverity.Warning,
                isEnabledByDefault: true);

            context.ReportDiagnostic(Diagnostic.Create(descriptor, null, ex.ToString()));
        }
    }

    private static void RegisterProperty(INamedTypeSymbol type, SourceCodeWriter sourceBuilder)
    {
        foreach (var propertySymbol in type.GetSelfAndBaseTypes().SelectMany(x => x.GetMembers()).OfType<IPropertySymbol>())
        {
            if (!propertySymbol.GetAttributes().Any(x => IsDataSourceGeneratorAttribute(x.AttributeClass, out _)))
            {
                continue;
            }

            sourceBuilder.WriteLine($"global::TUnit.Core.SourceRegistrar.RegisterProperty<{type.GloballyQualified()}>();");

            if (propertySymbol.Type is INamedTypeSymbol namedTypePropertySymbol)
            {
                RegisterProperty(namedTypePropertySymbol, sourceBuilder);
            }
        }
    }
}
