using Microsoft.CodeAnalysis;
using TUnit.Core.SourceGenerator.CodeGenerators.Helpers;
using TUnit.Core.SourceGenerator.CodeGenerators.Writers;
using TUnit.Core.SourceGenerator.Extensions;
using TUnit.Core.SourceGenerator.Models;

namespace TUnit.Core.SourceGenerator.CodeGenerators;

[Generator]
public class DynamicTestsGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var standardTests = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                "TUnit.Core.DynamicTestBuilderAttribute",
                predicate: static (_, _) => true,
                transform: static (ctx, _) => GetSemanticTargetForTestMethodGeneration(ctx))
            .Where(static m => m is not null);
        
        context.RegisterSourceOutput(standardTests, (sourceContext, data) => GenerateTests(sourceContext, data!));
    }

    static DynamicTestSourceDataModel? GetSemanticTargetForTestMethodGeneration(GeneratorAttributeSyntaxContext context)
    {
        if (context.TargetSymbol is not IMethodSymbol methodSymbol)
        {
            return null;
        }

        if (methodSymbol.IsAbstract)
        {
            return null;
        }

        if (methodSymbol.DeclaredAccessibility != Accessibility.Public)
        {
            return null;
        }

        return methodSymbol.ParseDynamicTestBuilders();
    }

    private void GenerateTests(SourceProductionContext context, DynamicTestSourceDataModel dynamicTestSource, string? prefix = null)
    {
        try
        {
            var className = dynamicTestSource.Class.Name;

            using var sourceBuilder = new SourceCodeWriter();

            sourceBuilder.WriteLine("// <auto-generated/>");
            sourceBuilder.WriteLine("#pragma warning disable");
            sourceBuilder.WriteLine("using global::System.Linq;");
            sourceBuilder.WriteLine("using global::System.Reflection;");
            sourceBuilder.WriteLine("using global::TUnit.Core;");
            sourceBuilder.WriteLine("using global::TUnit.Core.Extensions;");
            sourceBuilder.WriteLine();
            sourceBuilder.WriteLine("namespace TUnit.SourceGenerated;");
            sourceBuilder.WriteLine();
            sourceBuilder.WriteLine("[global::System.Diagnostics.StackTraceHidden]");
            sourceBuilder.WriteLine("[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]");
            sourceBuilder.WriteLine(
                $"file partial class {className} : global::TUnit.Core.Interfaces.SourceGenerator.IDynamicTestSource");
            sourceBuilder.WriteLine("{");

            sourceBuilder.WriteLine("[global::System.Runtime.CompilerServices.ModuleInitializer]");
            sourceBuilder.WriteLine("public static void Initialise()");
            sourceBuilder.WriteLine("{");
            sourceBuilder.WriteLine($"global::TUnit.Core.SourceRegistrar.RegisterDynamic(new {className}());");
            sourceBuilder.WriteLine("}");

            sourceBuilder.WriteLine(
                "public global::System.Collections.Generic.IReadOnlyList<DynamicTest> CollectTests(string sessionId)");
            sourceBuilder.WriteLine("{");

            sourceBuilder.WriteLine("try");
            sourceBuilder.WriteLine("{");

            sourceBuilder.WriteLine
            (
                $"""
                 var context = new global::TUnit.Core.DynamicTestBuilderContext(@"{dynamicTestSource.FilePath}", {dynamicTestSource.LineNumber});
                 """
            );

            var receiver = dynamicTestSource.Method.IsStatic
                ? dynamicTestSource.Class.GloballyQualified()
                : $"new {dynamicTestSource.Class.GloballyQualified()}()";

            sourceBuilder.WriteLine($"{receiver}.{dynamicTestSource.Method.Name}(context);");
            
            sourceBuilder.WriteLine("return context.Tests;");
            
            sourceBuilder.WriteLine("}");
            sourceBuilder.WriteLine("catch (global::System.Exception exception)");
            sourceBuilder.WriteLine("{");
            FailedTestInitializationWriter.GenerateFailedTestCode(sourceBuilder, dynamicTestSource);
            sourceBuilder.WriteLine("}");
            
            sourceBuilder.WriteLine("}");

            sourceBuilder.WriteLine("}");

            context.AddSource($"Dynamic-{className}-{Guid.NewGuid():N}.Generated.cs", sourceBuilder.ToString());
        }
        catch (Exception ex)
        {
            var descriptor = new DiagnosticDescriptor(id: "TUnit0000",
                title: "Error Generating Source",
                messageFormat: "{0}",
                category: "SourceGenerator",
                DiagnosticSeverity.Error,
                isEnabledByDefault: true);

            context.ReportDiagnostic(Diagnostic.Create(descriptor, null, ex.ToString()));
        }
    }
}