using TUnit.Core;
using TUnit.Core.Interfaces;

namespace TUnit.FsCheck;

/// <summary>
/// Marks a test method as an FsCheck property-based test.
/// The test method parameters will be generated by FsCheck and the test
/// will be run multiple times with different generated values.
/// </summary>
/// <remarks>
/// This attribute must be used together with the <see cref="TestAttribute"/>.
/// Example:
/// <code>
/// [Test, FsCheckProperty]
/// public bool MyProperty(int value) => value * 0 == 0;
/// </code>
/// </remarks>
[AttributeUsage(AttributeTargets.Method)]
public class FsCheckPropertyAttribute : Attribute, ITestRegisteredEventReceiver, IDataSourceAttribute
{

    /// <summary>
    /// The maximum number of tests to run. Default is 100.
    /// </summary>
    public int MaxTest { get; set; } = 100;

    /// <summary>
    /// The maximum number of rejected tests (tests that failed the precondition) before failing.
    /// </summary>
    public int MaxFail { get; set; } = 1000;

    /// <summary>
    /// The starting size for test generation. Size increases linearly between StartSize and EndSize.
    /// </summary>
    public int StartSize { get; set; } = 1;

    /// <summary>
    /// The ending size for test generation. Size increases linearly between StartSize and EndSize.
    /// </summary>
    public int EndSize { get; set; } = 100;

    /// <summary>
    /// If set, replay a previous run using the values FsCheck reports on failure.
    /// Format: "seed,gamma" replays the whole run; "seed,gamma,size" replays only the failing step.
    /// The parentheses FsCheck prints around these values are allowed. Any other value fails the test.
    /// </summary>
    public string? Replay { get; set; }

    /// <summary>
    /// If true, write every generated argument and every shrink step to the test output.
    /// </summary>
    public bool Verbose { get; set; }

    /// <summary>
    /// If true, suppress FsCheck's "Ok, passed N tests." summary on passing tests.
    /// </summary>
    public bool QuietOnSuccess { get; set; }

    /// <summary>
    /// The degree of parallelism FsCheck uses to invoke the property (its <c>ParallelRunConfig.MaxDegreeOfParallelism</c>).
    /// Default is 1; any value below 2 invokes the property sequentially.
    /// Above 1, the property must be safe to invoke concurrently on the same class instance.
    /// </summary>
    public int Parallelism { get; set; } = 1;

    /// <summary>
    /// Types containing Arbitrary instances to use for generating test data.
    /// </summary>
    public Type[]? Arbitrary { get; set; }

    /// <summary>
    /// Gets the order in which this event receiver is executed.
    /// </summary>
    public int Order => 0;

    /// <summary>
    /// Not used - FsCheck generates its own data during test execution.
    /// This property exists to satisfy the IDataSourceAttribute interface.
    /// </summary>
    public bool SkipIfEmpty { get; set; }

    /// <summary>
    /// Not used - FsCheck generates its own data during test execution (there are no discovery-time rows
    /// to defer), so this is always false. Exists to satisfy the IDataSourceAttribute interface.
    /// </summary>
    public bool DeferEnumeration { get => false; set { } }

    /// <summary>
    /// Called when the test is registered. Sets up the FsCheck property executor.
    /// </summary>
    public ValueTask OnTestRegistered(TestRegisteredContext context)
    {
        context.SetTestExecutor(new FsCheckPropertyTestExecutor(this));
        return default;
    }

    /// <summary>
    /// Returns placeholder data - actual test data is generated by FsCheck during test execution.
    /// </summary>
#pragma warning disable CS1998 // Async method lacks 'await' operators
    async IAsyncEnumerable<Func<Task<object?[]?>>> IDataSourceAttribute.GetDataRowsAsync(DataGeneratorMetadata dataGeneratorMetadata)
#pragma warning restore CS1998
    {
        // Return null array as placeholder - the FsCheckPropertyTestExecutor will generate actual data
        yield return () => Task.FromResult<object?[]?>(null);
    }
}
