using TUnit.Mocks.SourceGenerator.Models;

namespace TUnit.Mocks.SourceGenerator.Builders;

internal static class MockStaticExtensionBuilder
{
    public static string Build(MockTypeModel model)
    {
        if (!MockWrapperTypeBuilder.CanGenerateWrapper(model))
            return string.Empty;

        var writer = new CodeWriter();
        var safeName = MockImplBuilder.GetCompositeSafeName(model);

        writer.AppendLine("// <auto-generated/>");
        writer.AppendLine("#nullable enable");
        writer.AppendLine();

        using (writer.Block("namespace TUnit.Mocks"))
        {
            using (writer.Block($"public static class {safeName}_MockStaticExtension"))
            {
                using (writer.Block($"extension({model.FullyQualifiedName})"))
                {
                    writer.AppendLine("[global::System.Runtime.CompilerServices.OverloadResolutionPriority(1)]");
                    using (writer.Block($"public static global::TUnit.Mocks.Generated.{safeName}_Mock Mock(global::TUnit.Mocks.MockBehavior behavior = global::TUnit.Mocks.MockBehavior.Loose)"))
                    {
                        writer.AppendLine($"return (global::TUnit.Mocks.Generated.{safeName}_Mock)global::TUnit.Mocks.Generated.{safeName}_MockFactory.Create(behavior, []);");
                    }
                }
            }
        }

        return writer.ToString();
    }
}
