using System.Linq;
using TUnit.Mocks.SourceGenerator.Models;
using static TUnit.Mocks.SourceGenerator.IdentifierEscaping;

namespace TUnit.Mocks.SourceGenerator.Builders;

internal static class MockWrapperTypeBuilder
{
    /// <summary>
    /// Whether a typed wrapper (IFoo_Mock : Mock&lt;IFoo&gt;, IFoo) can be generated for this model.
    /// False for multi-interface mocks, static-abstract types, and interfaces with
    /// ref-struct-returning properties that can't be forwarded.
    /// </summary>
    public static bool CanGenerateWrapper(MockTypeModel model)
    {
        if (model.AdditionalInterfaceNames.Length > 0 || model.HasStaticAbstractMembers)
            return false;

        if (model.Properties.Any(p => !p.IsStaticAbstract && p.IsRefStructReturn))
            return false;

        return true;
    }

    public static string Build(MockTypeModel model)
    {
        if (!CanGenerateWrapper(model))
            return string.Empty;

        var writer = new CodeWriter();
        var safeName = MockImplBuilder.GetCompositeShortSafeName(model);
        var memberSafeName = MockImplBuilder.GetSafeName(model.FullyQualifiedName);
        var mockNamespace = MockImplBuilder.GetMockNamespace(model);
        var mockableType = MockImplBuilder.GetMockableTypeName(model);
        var typeParams = MockImplBuilder.GetTypeParameterList(model);
        var constraints = MockImplBuilder.GetConstraintClauses(model);

        writer.AppendLine("// <auto-generated/>");
        writer.AppendLine("#pragma warning disable");
        writer.AppendLine("#nullable enable");
        writer.AppendLine();

        using (writer.OptionalNamespaceBlock(mockNamespace))
        {
            using (writer.Block($"{model.Visibility} sealed class {safeName}Mock{typeParams} : global::TUnit.Mocks.Mock<{mockableType}>, {model.FullyQualifiedName}{constraints}"))
            {
                writer.AppendLine("[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]");
                writer.AppendLine($"internal {safeName}Mock({mockableType} mockObject, global::TUnit.Mocks.MockEngine<{mockableType}> engine)");
                writer.AppendLine("    : base(mockObject, engine) { }");

                foreach (var method in model.Methods)
                {
                    if (method.IsStaticAbstract) continue;
                    writer.AppendLine();
                    GenerateMethodForwarding(writer, method, model);

                    if (model.TypeParameters.Length > 0 && method.TypeParameters.Length > 0)
                    {
                        writer.AppendLine();
                        MockMembersBuilder.GenerateGenericMethodMembersForWrapper(writer, method, model, memberSafeName);
                    }
                }

                foreach (var prop in model.Properties)
                {
                    if (prop.IsStaticAbstract) continue;
                    writer.AppendLine();
                    if (prop.IsIndexer)
                    {
                        GenerateIndexerForwarding(writer, prop, model);
                    }
                    else
                    {
                        GeneratePropertyForwarding(writer, prop, model);
                    }
                }

                foreach (var evt in model.Events)
                {
                    if (evt.IsStaticAbstract) continue;
                    writer.AppendLine();
                    GenerateEventForwarding(writer, evt, model);
                }
            }
        }

        return writer.ToString();
    }

    private static void GenerateMethodForwarding(CodeWriter writer, MockMemberModel method, MockTypeModel model)
    {
        var interfaceName = method.ExplicitInterfaceName ?? method.DeclaringInterfaceName ?? model.FullyQualifiedName;
        var paramList = MockImplBuilder.GetParameterList(method);
        var typeParams = MockImplBuilder.GetTypeParameterList(method);
        var constraints = MockImplBuilder.GetConstraintClauses(method, forExplicitImplementation: true);
        var argPassList = MockImplBuilder.GetArgPassList(method);
        var returnType = (method.IsVoid && !method.IsAsync) ? "void" : method.ReturnType;

        // When the method is an explicit interface impl on the underlying object,
        // we must cast to call the correct method (e.g. ((IEnumerable)Object).GetEnumerator()).
        var target = method.ExplicitInterfaceName is not null
            ? $"(({method.ExplicitInterfaceName})Object)"
            : "Object";

        // Copy the source member's [Obsolete] attribute onto the forward so the call to
        // Object.{name}(...) inside this method is allowed by the compiler (a member
        // marked [Obsolete] may freely call other obsolete members, suppressing CS0618/CS0612).
        writer.AppendLineIfNotEmpty(method.ObsoleteAttribute);

        if (method.IsVoid && !method.IsAsync)
        {
            using (writer.Block($"{returnType} {interfaceName}.{EscapeIdentifier(method.Name)}{typeParams}({paramList}){constraints}"))
            {
                writer.AppendLine($"{target}.{EscapeIdentifier(method.Name)}{typeParams}({argPassList});");
            }
        }
        else
        {
            writer.AppendLine($"{returnType} {interfaceName}.{EscapeIdentifier(method.Name)}{typeParams}({paramList}){constraints} => {target}.{EscapeIdentifier(method.Name)}{typeParams}({argPassList});");
        }
    }

    private static void GeneratePropertyForwarding(CodeWriter writer, MockMemberModel prop, MockTypeModel model)
    {
        var interfaceName = GetForwardingInterfaceName(prop, model);
        var returnType = prop.ReturnType;
        var target = GetForwardingTarget(prop);

        writer.AppendLineIfNotEmpty(prop.ObsoleteAttribute);

        // Per-accessor [Obsolete] is injected inline so the property line stays a one-liner.
        var getterAttr = GetAccessorObsoletePrefix(prop.GetterObsoleteAttribute);
        var setterAttr = GetAccessorObsoletePrefix(prop.SetterObsoleteAttribute);
        var getter = prop.HasGetter ? $"{getterAttr}get => {target}.{EscapeIdentifier(prop.Name)}; " : "";
        var setter = prop.HasSetter ? $"{setterAttr}set => {target}.{EscapeIdentifier(prop.Name)} = value; " : "";

        writer.AppendLine($"{returnType} {interfaceName}.{EscapeIdentifier(prop.Name)} {{ {getter}{setter}}}");
    }

    private static void GenerateIndexerForwarding(CodeWriter writer, MockMemberModel prop, MockTypeModel model)
    {
        var interfaceName = GetForwardingInterfaceName(prop, model);
        var returnType = prop.ReturnType;
        var paramList = MockImplBuilder.GetParameterList(prop);
        var argPassList = MockImplBuilder.GetArgPassList(prop);
        var target = GetForwardingTarget(prop);

        writer.AppendLineIfNotEmpty(prop.ObsoleteAttribute);

        var getterAttr = GetAccessorObsoletePrefix(prop.GetterObsoleteAttribute);
        var setterAttr = GetAccessorObsoletePrefix(prop.SetterObsoleteAttribute);
        var getter = prop.HasGetter ? $"{getterAttr}get => {target}[{argPassList}]; " : "";
        var setter = prop.HasSetter ? $"{setterAttr}set => {target}[{argPassList}] = value; " : "";

        writer.AppendLine($"{returnType} {interfaceName}.this[{paramList}] {{ {getter}{setter}}}");
    }

    private static string GetForwardingInterfaceName(MockMemberModel member, MockTypeModel model)
        => member.ExplicitInterfaceName ?? member.DeclaringInterfaceName ?? model.FullyQualifiedName;

    // When the member is an explicit interface impl on the underlying object,
    // we must cast to access the correct member.
    private static string GetForwardingTarget(MockMemberModel member)
        => member.ExplicitInterfaceName is not null
            ? $"(({member.ExplicitInterfaceName})Object)"
            : "Object";

    private static string GetAccessorObsoletePrefix(string obsoleteAttribute)
        => obsoleteAttribute.Length > 0 ? obsoleteAttribute + " " : "";

    private static void GenerateEventForwarding(CodeWriter writer, MockEventModel evt, MockTypeModel model)
    {
        var interfaceName = evt.ExplicitInterfaceName ?? evt.DeclaringInterfaceName ?? model.FullyQualifiedName;

        writer.AppendLineIfNotEmpty(evt.ObsoleteAttribute);
        writer.AppendLine($"event {evt.EventHandlerType} {interfaceName}.{EscapeIdentifier(evt.Name)} {{ add => Object.{EscapeIdentifier(evt.Name)} += value; remove => Object.{EscapeIdentifier(evt.Name)} -= value; }}");
    }

}
