using System;
using System.Linq;
using TUnit.Mocks.SourceGenerator.Models;

namespace TUnit.Mocks.SourceGenerator.Builders;

internal static class MockStaticExtensionBuilder
{
    public static string Build(MockTypeModel model)
    {
        if (!MockWrapperTypeBuilder.CanGenerateWrapper(model))
            return string.Empty;

        var shortName = MockImplBuilder.GetCompositeShortSafeName(model);
        var mockNamespace = MockImplBuilder.GetMockNamespace(model);

        return BuildCore(model, (writer, mockableType, visibility) =>
        {
            using (writer.Block($"{visibility} static global::{mockNamespace}.{shortName}Mock Mock(global::TUnit.Mocks.MockBehavior behavior = global::TUnit.Mocks.MockBehavior.Loose)"))
            {
                writer.AppendLine($"return (global::{mockNamespace}.{shortName}Mock)global::TUnit.Mocks.Mock.Of<{mockableType}>(behavior);");
            }
        });
    }

    public static string BuildForPartialMock(MockTypeModel model)
    {
        return BuildCore(model, (writer, mockableType, visibility) =>
        {
            using (writer.Block($"{visibility} static global::TUnit.Mocks.Mock<{mockableType}> Mock(global::TUnit.Mocks.MockBehavior behavior = global::TUnit.Mocks.MockBehavior.Loose)"))
            {
                writer.AppendLine($"return global::TUnit.Mocks.Mock.Of<{mockableType}>(behavior);");
            }

            foreach (var ctor in model.Constructors)
            {
                if (ctor.Parameters.Length == 0)
                    continue;

                // Skip constructors with ref struct, ref, or out parameters — they can't be passed through params object[]
                if (ctor.Parameters.Any(p => p.IsRefStruct || p.Direction is ParameterDirection.Ref or ParameterDirection.Out))
                    continue;

                writer.AppendLine();

                var paramList = string.Join(", ",
                    ctor.Parameters.Select(FormatParameter)
                        .Append($"global::TUnit.Mocks.MockBehavior behavior = global::TUnit.Mocks.MockBehavior.Loose"));

                var argList = string.Join(", ",
                    ctor.Parameters.Select(p => p.Name));

                using (writer.Block($"{visibility} static global::TUnit.Mocks.Mock<{mockableType}> Mock({paramList})"))
                {
                    writer.AppendLine($"return global::TUnit.Mocks.Mock.Of<{mockableType}>(behavior, {argList});");
                }
            }
        });
    }

    private static string BuildCore(MockTypeModel model, Action<CodeWriter, string, string> writeBody)
    {
        var writer = new CodeWriter();
        var extensionClassName = MockImplBuilder.GetCompositeSafeName(model);
        var mockableType = MockImplBuilder.GetMockableTypeName(model);

        writer.AppendLine("// <auto-generated/>");
        writer.AppendLine("#nullable enable");
        writer.AppendLine();

        using (writer.Block("namespace TUnit.Mocks"))
        {
            using (writer.Block($"{model.Visibility} static class {extensionClassName}_MockStaticExtension"))
            {
                using (writer.Block($"extension({model.FullyQualifiedName})"))
                {
                    writeBody(writer, mockableType, model.Visibility);
                }
            }
        }

        return writer.ToString();
    }

    private static string FormatParameter(MockParameterModel p)
    {
        var prefix = p.Direction == ParameterDirection.In_Readonly ? "in " : "";
        return $"{prefix}{p.FullyQualifiedType} {p.Name}";
    }
}
