using System.Diagnostics;
using FsCheck;
using FsCheck.Fluent;
using TUnit.Core;
using TUnit.FsCheck;

namespace TUnit.Example.FsCheck.TestProject;

/// <summary>
/// Verifies that FsCheck properties receive the TUnit timeout-backed CancellationToken
/// rather than a token generated by FsCheck's default reflection-based arbitrary.
/// </summary>
[Timeout(10_000)]
public sealed class CancellationTokenBehaviourTests
{
    /// <summary>
    /// 100 invocations check that the CT is NOT pre-cancelled at entry. Before the fix,
    /// FsCheck's default arbitrary produced a pre-cancelled token on roughly half of
    /// invocations. No <see cref="FsCheckPropertyAttribute.Arbitrary"/> is specified,
    /// so only the default registration applies.
    /// </summary>
    [Test, FsCheckProperty(MaxTest = 100)]
    public bool CancellationTokenIsNotPreCancelled(CancellationToken cancellationToken)
    {
        return !cancellationToken.IsCancellationRequested;
    }

    /// <summary>
    /// Verifies the token identity: the CT passed to the property IS the one from
    /// <see cref="TestContext.Current"/>, not just any non-cancelled token.
    /// </summary>
    [Test, FsCheckProperty(MaxTest = 1)]
    public bool CancellationTokenIsTestContextToken(CancellationToken cancellationToken)
    {
        var expected = TestContext.Current?.Execution.CancellationToken ?? CancellationToken.None;
        return cancellationToken == expected;
    }

    /// <summary>
    /// A user-supplied <see cref="Arbitrary{T}"/> via <see cref="FsCheckPropertyAttribute.Arbitrary"/>
    /// takes precedence over the default CancellationToken arbitrary.
    /// </summary>
    [Test, FsCheckProperty(MaxTest = 10, Arbitrary = new[] { typeof(AlwaysNoneTokenArbitrary) })]
    public bool UserSuppliedArbitraryOverridesDefault(CancellationToken cancellationToken)
    {
        return cancellationToken == CancellationToken.None;
    }

    /// <summary>
    /// A user-supplied arbitrary for an unrelated type does not displace the default
    /// CancellationToken registration; both apply alongside each other.
    /// </summary>
    [Test, FsCheckProperty(MaxTest = 10, Arbitrary = new[] { typeof(PositiveIntArbitrary) })]
    public bool UserArbitraryForDifferentTypeDoesNotBypassDefault(int x, CancellationToken cancellationToken)
    {
        return x > 0 && !cancellationToken.IsCancellationRequested;
    }

    /// <summary>
    /// An empty <see cref="FsCheckPropertyAttribute.Arbitrary"/> array does not bypass
    /// the default registration; properties still receive the test-context CancellationToken.
    /// </summary>
    [Test, FsCheckProperty(MaxTest = 1, Arbitrary = new Type[0])]
    public bool EmptyArbitraryArrayStillUsesDefault(CancellationToken cancellationToken)
    {
        return !cancellationToken.IsCancellationRequested;
    }

    /// <summary>
    /// FsCheck properties without a CancellationToken parameter are unaffected by the fix.
    /// </summary>
#pragma warning disable TUnit0015 // intentionally omitted to verify the no-CT path
    [Test, FsCheckProperty(MaxTest = 50)]
    public bool NoCancellationTokenParameter_UnchangedBehaviour(int x, int y)
    {
        return x + y == y + x;
    }
#pragma warning restore TUnit0015

    /// <summary>
    /// <c>[Timeout(500)]</c> + an await on the CT for 5s. If the CT is the timeout one,
    /// the await is cooperatively cancelled at ~500ms. Before the fix, FsCheck injected its
    /// own token and the await either threw immediately (pre-cancelled) or ran to completion.
    /// </summary>
    [Test, FsCheckProperty(MaxTest = 1)]
    [Timeout(500)]
    public async Task<bool> CooperativeCancellationViaTimeout(CancellationToken cancellationToken)
    {
        var stopwatch = Stopwatch.StartNew();
        try
        {
            await Task.Delay(5000, cancellationToken).ConfigureAwait(false);
            return false;
        }
        catch (OperationCanceledException)
        {
            return stopwatch.Elapsed.TotalMilliseconds is >= 200 and <= 2_000;
        }
    }
}

/// <summary>
/// Test arbitrary that always returns <see cref="CancellationToken.None"/>.
/// Used by <see cref="CancellationTokenBehaviourTests.UserSuppliedArbitraryOverridesDefault"/>
/// to verify that user-supplied arbitraries take precedence over the default.
/// </summary>
internal static class AlwaysNoneTokenArbitrary
{
    /// <summary>Always returns <see cref="CancellationToken.None"/>.</summary>
    public static Arbitrary<CancellationToken> CancellationToken()
    {
        return Arb.From(Gen.Constant(System.Threading.CancellationToken.None));
    }
}
