using System.Runtime.CompilerServices;
using TUnit.Assertions.AssertConditions.Interfaces;
using TUnit.Assertions.AssertionBuilders;
using TUnit.Assertions.Assertions.Enums.Conditions;
using TUnit.Assertions.Extensions;

namespace TUnit.Assertions.Assertions.Enums;

public static class EnumHasExtensions
{
    public static InvokableValueAssertionBuilder<TEnum> HasFlag<TEnum>(this IValueSource<TEnum> valueSource, TEnum expected, [CallerArgumentExpression(nameof(expected))] string? doNotPopulateThisValue1 = null)
    where TEnum : Enum
    {
        return valueSource.RegisterAssertion(new EnumHasFlagAssertCondition<TEnum>(expected),
            [doNotPopulateThisValue1]);
    }

    public static InvokableValueAssertionBuilder<TEnum> DoesNotHaveFlag<TEnum>(this IValueSource<TEnum> valueSource, TEnum expected, [CallerArgumentExpression(nameof(expected))] string? doNotPopulateThisValue1 = null)
        where TEnum : Enum
    {
        return valueSource.RegisterAssertion(new EnumDoesNotHaveFlagAssertCondition<TEnum>(expected),
            [doNotPopulateThisValue1]);
    }

    public static InvokableValueAssertionBuilder<TEnum> HasSameNameAs<TEnum, TExpected>(this IValueSource<TEnum> valueSource, TExpected expected, [CallerArgumentExpression(nameof(expected))] string? doNotPopulateThisValue1 = null)
        where TEnum : Enum
        where TExpected : Enum
    {
        return valueSource.RegisterAssertion(new EnumHasSameNameAsCondition<TEnum, TExpected>(expected),
            [doNotPopulateThisValue1]);
    }

    public static InvokableValueAssertionBuilder<TEnum> DoesNotHaveSameNameAs<TEnum, TExpected>(this IValueSource<TEnum> valueSource, TExpected expected, [CallerArgumentExpression(nameof(expected))] string? doNotPopulateThisValue1 = null)
        where TEnum : Enum
        where TExpected : Enum
    {
        return valueSource.RegisterAssertion(new EnumDoesNotHaveSameNameAsCondition<TEnum, TExpected>(expected),
            [doNotPopulateThisValue1]);
    }

    // IsDefined and IsNotDefined are now generated by the source generator

    public static InvokableValueAssertionBuilder<TEnum> HasSameValueAs<TEnum, TExpected>(this IValueSource<TEnum> valueSource, TExpected expected, [CallerArgumentExpression(nameof(expected))] string? doNotPopulateThisValue1 = null)
        where TEnum : Enum
        where TExpected : Enum
    {
        return valueSource.RegisterAssertion(new EnumHasSameValueAsCondition<TEnum, TExpected>(expected),
            [doNotPopulateThisValue1]);
    }

    public static InvokableValueAssertionBuilder<TEnum> DoesNotHaveSameValueAs<TEnum, TExpected>(this IValueSource<TEnum> valueSource, TExpected expected, [CallerArgumentExpression(nameof(expected))] string? doNotPopulateThisValue1 = null)
        where TEnum : Enum
        where TExpected : Enum
    {
        return valueSource.RegisterAssertion(new EnumDoesNotHaveSameValueAsCondition<TEnum, TExpected>(expected),
            [doNotPopulateThisValue1]);
    }
}
