using TUnit.Mock.SourceGenerator.Models;

namespace TUnit.Mock.SourceGenerator.Builders;

internal static class MockVerifyBuilder
{
    public static string Build(MockTypeModel model)
    {
        var writer = new CodeWriter();
        var safeName = MockImplBuilder.GetSafeName(model.Name);

        writer.AppendLine("// <auto-generated/>");
        writer.AppendLine("#nullable enable");
        writer.AppendLine();

        using (writer.Block("namespace TUnit.Mock.Generated"))
        {
            using (writer.Block($"public sealed class {safeName}_MockVerify"))
            {
                writer.AppendLine($"private readonly global::TUnit.Mock.MockEngine<{model.FullyQualifiedName}> _engine;");
                writer.AppendLine();
                writer.AppendLine($"internal {safeName}_MockVerify(global::TUnit.Mock.MockEngine<{model.FullyQualifiedName}> engine) => _engine = engine;");

                // Methods
                foreach (var method in model.Methods)
                {
                    writer.AppendLine();
                    GenerateVerifyMethod(writer, method, model);
                }

                // Properties
                foreach (var prop in model.Properties)
                {
                    if (prop.IsIndexer) continue;
                    if (!prop.HasGetter && !prop.HasSetter) continue;
                    writer.AppendLine();
                    GenerateVerifyProperty(writer, prop, model);
                }
            }
        }

        return writer.ToString();
    }

    private static void GenerateVerifyMethod(CodeWriter writer, MockMemberModel method, MockTypeModel model)
    {
        var paramList = GetArgParameterList(method);
        var typeParams = GetTypeParameterList(method);
        var constraints = GetConstraintClauses(method);

        using (writer.Block($"public global::TUnit.Mock.Verification.ICallVerification {method.Name}{typeParams}({paramList}){constraints}"))
        {
            // Build matchers array
            var nonOutParams = method.Parameters.Where(p => p.Direction != ParameterDirection.Out).ToList();

            if (nonOutParams.Count == 0)
            {
                writer.AppendLine("var matchers = global::System.Array.Empty<global::TUnit.Mock.Arguments.IArgumentMatcher>();");
            }
            else
            {
                var matcherArgs = string.Join(", ", nonOutParams.Select(p => $"{p.Name}.Matcher"));
                writer.AppendLine($"var matchers = new global::TUnit.Mock.Arguments.IArgumentMatcher[] {{ {matcherArgs} }};");
            }

            writer.AppendLine($"return new global::TUnit.Mock.Verification.CallVerificationBuilder<{model.FullyQualifiedName}>(_engine, {method.MemberId}, \"{method.Name}\", matchers);");
        }
    }

    private static void GenerateVerifyProperty(CodeWriter writer, MockMemberModel prop, MockTypeModel model)
    {
        // Getter verification
        if (prop.HasGetter)
        {
            using (writer.Block($"public global::TUnit.Mock.Verification.ICallVerification {prop.Name}_Get()"))
            {
                writer.AppendLine("var matchers = global::System.Array.Empty<global::TUnit.Mock.Arguments.IArgumentMatcher>();");
                writer.AppendLine($"return new global::TUnit.Mock.Verification.CallVerificationBuilder<{model.FullyQualifiedName}>(_engine, {prop.MemberId}, \"get_{prop.Name}\", matchers);");
            }
        }

        // Setter verification — accepts Arg<T> to match the set value
        if (prop.HasSetter)
        {
            var setterMemberId = prop.MemberId + 10000;

            using (writer.Block($"public global::TUnit.Mock.Verification.ICallVerification {prop.Name}_Set(global::TUnit.Mock.Arguments.Arg<{prop.ReturnType}> value)"))
            {
                writer.AppendLine("var matchers = new global::TUnit.Mock.Arguments.IArgumentMatcher[] { value.Matcher };");
                writer.AppendLine($"return new global::TUnit.Mock.Verification.CallVerificationBuilder<{model.FullyQualifiedName}>(_engine, {setterMemberId}, \"set_{prop.Name}\", matchers);");
            }

            // Overload without value argument — matches any set call
            using (writer.Block($"public global::TUnit.Mock.Verification.ICallVerification {prop.Name}_Set()"))
            {
                writer.AppendLine($"return new global::TUnit.Mock.Verification.CallVerificationBuilder<{model.FullyQualifiedName}>(_engine, {setterMemberId}, \"set_{prop.Name}\", global::System.Array.Empty<global::TUnit.Mock.Arguments.IArgumentMatcher>());");
            }
        }
    }

    private static string GetArgParameterList(MockMemberModel method)
    {
        return string.Join(", ", method.Parameters
            .Where(p => p.Direction != ParameterDirection.Out)
            .Select(p => $"global::TUnit.Mock.Arguments.Arg<{p.FullyQualifiedType}> {p.Name}"));
    }

    private static string GetTypeParameterList(MockMemberModel method)
    {
        if (method.TypeParameters.Length == 0) return "";
        return "<" + string.Join(", ", method.TypeParameters.Select(tp => tp.Name)) + ">";
    }

    private static string GetConstraintClauses(MockMemberModel method)
    {
        var clauses = new List<string>();
        foreach (var tp in method.TypeParameters)
        {
            if (!string.IsNullOrEmpty(tp.Constraints))
            {
                clauses.Add($"where {tp.Name} : {tp.Constraints}");
            }
        }
        return clauses.Count > 0 ? " " + string.Join(" ", clauses) : "";
    }
}
