//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TUnit.Analyzers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TUnit.Analyzers.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t mix &apos;Or&apos; &amp; &apos;And&apos; operators in assertions.
        /// </summary>
        internal static string TUnit0001CodeFixTitle {
            get {
                return ResourceManager.GetString("TUnit0001CodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t mix &apos;Or&apos; &amp; &apos;And&apos; operators in assertions..
        /// </summary>
        internal static string TUnit0001Description {
            get {
                return ResourceManager.GetString("TUnit0001Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t mix &apos;Or&apos; &amp; &apos;And&apos; operators in assertions.
        /// </summary>
        internal static string TUnit0001MessageFormat {
            get {
                return ResourceManager.GetString("TUnit0001MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t mix &apos;Or&apos; &amp; &apos;And&apos; operators in assertions.
        /// </summary>
        internal static string TUnit0001Title {
            get {
                return ResourceManager.GetString("TUnit0001Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assert statements must be awaited.
        /// </summary>
        internal static string TUnit0002CodeFixTitle {
            get {
                return ResourceManager.GetString("TUnit0002CodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assert statements must be awaited..
        /// </summary>
        internal static string TUnit0002Description {
            get {
                return ResourceManager.GetString("TUnit0002Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assert statements must be awaited.
        /// </summary>
        internal static string TUnit0002MessageFormat {
            get {
                return ResourceManager.GetString("TUnit0002MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assert statements must be awaited.
        /// </summary>
        internal static string TUnit0002Title {
            get {
                return ResourceManager.GetString("TUnit0002Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The arguments for this test don&apos;t match the method argument types..
        /// </summary>
        internal static string TUnit0003Description {
            get {
                return ResourceManager.GetString("TUnit0003Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute argument types &apos;{0}&apos; don&apos;t match method parameter types &apos;{1}&apos;.
        /// </summary>
        internal static string TUnit0003MessageFormat {
            get {
                return ResourceManager.GetString("TUnit0003MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Data for Tests.
        /// </summary>
        internal static string TUnit0003Title {
            get {
                return ResourceManager.GetString("TUnit0003Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data provided for test..
        /// </summary>
        internal static string TUnit0004Description {
            get {
                return ResourceManager.GetString("TUnit0004Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data provided for test.
        /// </summary>
        internal static string TUnit0004MessageFormat {
            get {
                return ResourceManager.GetString("TUnit0004MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data provided for test.
        /// </summary>
        internal static string TUnit0004Title {
            get {
                return ResourceManager.GetString("TUnit0004Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data provided for test..
        /// </summary>
        internal static string TUnit0005Description {
            get {
                return ResourceManager.GetString("TUnit0005Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data provided for test.
        /// </summary>
        internal static string TUnit0005MessageFormat {
            get {
                return ResourceManager.GetString("TUnit0005MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data provided for test.
        /// </summary>
        internal static string TUnit0005Title {
            get {
                return ResourceManager.GetString("TUnit0005Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data source method found..
        /// </summary>
        internal static string TUnit0006Description {
            get {
                return ResourceManager.GetString("TUnit0006Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data source method found.
        /// </summary>
        internal static string TUnit0006MessageFormat {
            get {
                return ResourceManager.GetString("TUnit0006MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data source method found.
        /// </summary>
        internal static string TUnit0006Title {
            get {
                return ResourceManager.GetString("TUnit0006Title", resourceCulture);
            }
        }
    }
}
