//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TUnit.Analyzers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TUnit.Analyzers.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The arguments for this test don&apos;t match the method argument types..
        /// </summary>
        internal static string TUnit0001Description {
            get {
                return ResourceManager.GetString("TUnit0001Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute argument types &apos;{0}&apos; don&apos;t match method parameter types &apos;{1}&apos;.
        /// </summary>
        internal static string TUnit0001MessageFormat {
            get {
                return ResourceManager.GetString("TUnit0001MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Data for Tests.
        /// </summary>
        internal static string TUnit0001Title {
            get {
                return ResourceManager.GetString("TUnit0001Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data provided for test..
        /// </summary>
        internal static string TUnit0002Description {
            get {
                return ResourceManager.GetString("TUnit0002Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data provided for test.
        /// </summary>
        internal static string TUnit0002MessageFormat {
            get {
                return ResourceManager.GetString("TUnit0002MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data provided for test.
        /// </summary>
        internal static string TUnit0002Title {
            get {
                return ResourceManager.GetString("TUnit0002Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data provided for test..
        /// </summary>
        internal static string TUnit0003Description {
            get {
                return ResourceManager.GetString("TUnit0003Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data provided for test.
        /// </summary>
        internal static string TUnit0003MessageFormat {
            get {
                return ResourceManager.GetString("TUnit0003MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data provided for test.
        /// </summary>
        internal static string TUnit0003Title {
            get {
                return ResourceManager.GetString("TUnit0003Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data source method found..
        /// </summary>
        internal static string TUnit0004Description {
            get {
                return ResourceManager.GetString("TUnit0004Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data source method found.
        /// </summary>
        internal static string TUnit0004MessageFormat {
            get {
                return ResourceManager.GetString("TUnit0004MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data source method found.
        /// </summary>
        internal static string TUnit0004Title {
            get {
                return ResourceManager.GetString("TUnit0004Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter is not defined as nullable..
        /// </summary>
        internal static string TUnit0005Description {
            get {
                return ResourceManager.GetString("TUnit0005Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter &apos;{0}&apos; is not defined as nullable.
        /// </summary>
        internal static string TUnit0005MessageFormat {
            get {
                return ResourceManager.GetString("TUnit0005MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter is not defined as nullable.
        /// </summary>
        internal static string TUnit0005Title {
            get {
                return ResourceManager.GetString("TUnit0005Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data source doesn&apos;t match method argument type..
        /// </summary>
        internal static string TUnit0006Description {
            get {
                return ResourceManager.GetString("TUnit0006Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data source type {0} doesn&apos;t match the parameter type {1}.
        /// </summary>
        internal static string TUnit0006MessageFormat {
            get {
                return ResourceManager.GetString("TUnit0006MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data source doesn&apos;t match method argument type.
        /// </summary>
        internal static string TUnit0006Title {
            get {
                return ResourceManager.GetString("TUnit0006Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method must be static..
        /// </summary>
        internal static string TUnit0007Description {
            get {
                return ResourceManager.GetString("TUnit0007Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method must be static.
        /// </summary>
        internal static string TUnit0007MessageFormat {
            get {
                return ResourceManager.GetString("TUnit0007MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method must be static.
        /// </summary>
        internal static string TUnit0007Title {
            get {
                return ResourceManager.GetString("TUnit0007Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method must be public..
        /// </summary>
        internal static string TUnit0008Description {
            get {
                return ResourceManager.GetString("TUnit0008Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method must be public.
        /// </summary>
        internal static string TUnit0008MessageFormat {
            get {
                return ResourceManager.GetString("TUnit0008MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method must be public.
        /// </summary>
        internal static string TUnit0008Title {
            get {
                return ResourceManager.GetString("TUnit0008Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method cannot be abstract..
        /// </summary>
        internal static string TUnit0009Description {
            get {
                return ResourceManager.GetString("TUnit0009Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method cannot be abstract.
        /// </summary>
        internal static string TUnit0009MessageFormat {
            get {
                return ResourceManager.GetString("TUnit0009MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method cannot be abstract.
        /// </summary>
        internal static string TUnit0009Title {
            get {
                return ResourceManager.GetString("TUnit0009Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method should be parameterless..
        /// </summary>
        internal static string TUnit0010Description {
            get {
                return ResourceManager.GetString("TUnit0010Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method should be parameterless.
        /// </summary>
        internal static string TUnit0010MessageFormat {
            get {
                return ResourceManager.GetString("TUnit0010MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method should be parameterless.
        /// </summary>
        internal static string TUnit0010Title {
            get {
                return ResourceManager.GetString("TUnit0010Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method returns void..
        /// </summary>
        internal static string TUnit0011Description {
            get {
                return ResourceManager.GetString("TUnit0011Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method returns void.
        /// </summary>
        internal static string TUnit0011MessageFormat {
            get {
                return ResourceManager.GetString("TUnit0011MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method returns void.
        /// </summary>
        internal static string TUnit0011Title {
            get {
                return ResourceManager.GetString("TUnit0011Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no argument for the data source..
        /// </summary>
        internal static string TUnit0012Description {
            get {
                return ResourceManager.GetString("TUnit0012Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no argument for the data source.
        /// </summary>
        internal static string TUnit0012MessageFormat {
            get {
                return ResourceManager.GetString("TUnit0012MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no argument for the data source.
        /// </summary>
        internal static string TUnit0012Title {
            get {
                return ResourceManager.GetString("TUnit0012Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data source method must only have 1 matching parameter..
        /// </summary>
        internal static string TUnit0013Description {
            get {
                return ResourceManager.GetString("TUnit0013Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data source method must only have 1 matching parameter.
        /// </summary>
        internal static string TUnit0013MessageFormat {
            get {
                return ResourceManager.GetString("TUnit0013MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data source method must only have 1 matching parameter.
        /// </summary>
        internal static string TUnit0013Title {
            get {
                return ResourceManager.GetString("TUnit0013Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are conflicting test attributes..
        /// </summary>
        internal static string TUnit0014Description {
            get {
                return ResourceManager.GetString("TUnit0014Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are conflicting test attributes.
        /// </summary>
        internal static string TUnit0014MessageFormat {
            get {
                return ResourceManager.GetString("TUnit0014MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are conflicting test attributes.
        /// </summary>
        internal static string TUnit0014Title {
            get {
                return ResourceManager.GetString("TUnit0014Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing TimeoutAttribute cancellation token parameter..
        /// </summary>
        internal static string TUnit0015Description {
            get {
                return ResourceManager.GetString("TUnit0015Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing TimeoutAttribute cancellation token parameter.
        /// </summary>
        internal static string TUnit0015MessageFormat {
            get {
                return ResourceManager.GetString("TUnit0015MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing TimeoutAttribute cancellation token parameter.
        /// </summary>
        internal static string TUnit0015Title {
            get {
                return ResourceManager.GetString("TUnit0015Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method must not be static..
        /// </summary>
        internal static string TUnit0016Description {
            get {
                return ResourceManager.GetString("TUnit0016Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method must not be static.
        /// </summary>
        internal static string TUnit0016MessageFormat {
            get {
                return ResourceManager.GetString("TUnit0016MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method must not be static.
        /// </summary>
        internal static string TUnit0016Title {
            get {
                return ResourceManager.GetString("TUnit0016Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explicit attribute cannot be on both method and class..
        /// </summary>
        internal static string TUnit0017Description {
            get {
                return ResourceManager.GetString("TUnit0017Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explicit attribute cannot be on both method and class.
        /// </summary>
        internal static string TUnit0017MessageFormat {
            get {
                return ResourceManager.GetString("TUnit0017MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explicit attribute cannot be on both method and class.
        /// </summary>
        internal static string TUnit0017Title {
            get {
                return ResourceManager.GetString("TUnit0017Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test methods should not assign instance data. Consider making this static if you need to store it. And beware of race conditions if you haven&apos;t marked tests with [NotInParallel]..
        /// </summary>
        internal static string TUnit0018Description {
            get {
                return ResourceManager.GetString("TUnit0018Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test methods should not assign instance data.
        /// </summary>
        internal static string TUnit0018MessageFormat {
            get {
                return ResourceManager.GetString("TUnit0018MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test methods should not assign instance data.
        /// </summary>
        internal static string TUnit0018Title {
            get {
                return ResourceManager.GetString("TUnit0018Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing `DataDrivenTest` Attribute..
        /// </summary>
        internal static string TUnit0019Description {
            get {
                return ResourceManager.GetString("TUnit0019Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing `DataDrivenTest` Attribute.
        /// </summary>
        internal static string TUnit0019MessageFormat {
            get {
                return ResourceManager.GetString("TUnit0019MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing `DataDrivenTest` Attribute.
        /// </summary>
        internal static string TUnit0019Title {
            get {
                return ResourceManager.GetString("TUnit0019Title", resourceCulture);
            }
        }
    }
}
