using Microsoft.CodeAnalysis;
using TUnit.Mocks.SourceGenerator.Builders;
using TUnit.Mocks.SourceGenerator.Discovery;
using TUnit.Mocks.SourceGenerator.Models;

namespace TUnit.Mocks.SourceGenerator;

[Generator(LanguageNames.CSharp)]
public class MockGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Always emit the TUnit.Mocks.Generated namespace so that global usings never fail
        context.RegisterPostInitializationOutput(ctx =>
        {
            ctx.AddSource("TUnit.Mocks.Generated.Namespace.g.cs", """
                // <auto-generated/>
                #nullable enable

                namespace TUnit.Mocks.Generated;
                """);
        });

        // Step 1a: Find all Mock.Of<T>() invocations and transform to model arrays
        var mockTypes = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: MockTypeDiscovery.IsMockOfInvocation,
                transform: MockTypeDiscovery.TransformToModels)
            .SelectMany((models, _) => models);

        // Step 1b: Find all [assembly: GenerateMock(typeof(T))] attributes
        var attributeTypes = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                "TUnit.Mocks.GenerateMockAttribute",
                predicate: static (node, _) => true,
                transform: MockTypeDiscovery.TransformGenerateMockAttribute)
            .SelectMany((models, _) => models);

        // Step 1c: Find all IFoo.Mock() static extension invocations
        var extensionTypes = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: MockTypeDiscovery.IsMockExtensionInvocation,
                transform: MockTypeDiscovery.TransformMockExtensionInvocation)
            .SelectMany((models, _) => models);

        // Step 2: Merge all sources and deduplicate
        var distinctTypes = mockTypes
            .Collect()
            .Combine(attributeTypes.Collect())
            .Combine(extensionTypes.Collect())
            .SelectMany((pair, _) =>
            {
                var (mockOfAndAttribute, extensionInvocations) = pair;
                var (mockOfTypes, attributeTypes) = mockOfAndAttribute;
                var set = new HashSet<MockTypeModel>();
                foreach (var m in mockOfTypes) set.Add(m);
                foreach (var m in attributeTypes) set.Add(m);
                foreach (var m in extensionInvocations) set.Add(m);
                return set;
            });

        // Step 3: Generate source for each unique type
        context.RegisterSourceOutput(distinctTypes, (spc, model) =>
        {
            if (model.IsDelegateType)
            {
                // Delegate mock: generate members and delegate factory (no impl class)
                GenerateDelegateMock(spc, model);
            }
            else if (model.IsWrapMock)
            {
                // Wrap mock: generate wrap impl, wrap factory, plus members
                GenerateWrapMock(spc, model);
            }
            else if (model.AdditionalInterfaceNames.Length > 0)
            {
                // Multi-interface mock: generate ONLY impl + factory
                // Members/raise come from the single-type model (also emitted)
                GenerateMultiInterfaceMock(spc, model);
            }
            else
            {
                // Single-type mock: generate everything
                GenerateSingleTypeMock(spc, model);
            }
        });
    }

    private static void GenerateSingleTypeMock(SourceProductionContext spc, MockTypeModel model)
    {
        var fileName = GetSafeFileName(model);

        if (model.HasStaticAbstractMembers)
        {
            var bridgeSource = MockBridgeBuilder.Build(model);
            spc.AddSource($"{fileName}_MockBridge.g.cs", bridgeSource);
        }

        GenerateImplFactoryMembersAndEvents(spc, model, fileName);

        if (model.IsInterface)
        {
            var wrapperSource = MockWrapperTypeBuilder.Build(model);
            if (!string.IsNullOrEmpty(wrapperSource))
            {
                spc.AddSource($"{fileName}_Mock.g.cs", wrapperSource);

                var extensionSource = MockStaticExtensionBuilder.Build(model);
                if (!string.IsNullOrEmpty(extensionSource))
                {
                    spc.AddSource($"{fileName}_MockStaticExtension.g.cs", extensionSource);
                }
            }
        }
    }

    private static void GenerateDelegateMock(SourceProductionContext spc, MockTypeModel model)
    {
        var fileName = GetSafeFileName(model);

        var membersSource = MockMembersBuilder.Build(model);
        spc.AddSource($"{fileName}_MockMembers.g.cs", membersSource);

        var factorySource = MockDelegateFactoryBuilder.Build(model);
        spc.AddSource($"{fileName}_MockDelegateFactory.g.cs", factorySource);
    }

    private static void GenerateWrapMock(SourceProductionContext spc, MockTypeModel model)
    {
        var fileName = GetSafeFileName(model);
        GenerateImplFactoryMembersAndEvents(spc, model, fileName);
    }

    private static void GenerateMultiInterfaceMock(SourceProductionContext spc, MockTypeModel model)
    {
        var fileName = GetSafeFileName(model);
        var implFactorySource = BuildCombinedImplAndFactory(model);
        spc.AddSource($"{fileName}_MockImplFactory.g.cs", implFactorySource);
    }

    private static void GenerateImplFactoryMembersAndEvents(SourceProductionContext spc, MockTypeModel model, string fileName)
    {
        var implFactorySource = BuildCombinedImplAndFactory(model);
        spc.AddSource($"{fileName}_MockImplFactory.g.cs", implFactorySource);

        var membersSource = MockMembersBuilder.Build(model);
        spc.AddSource($"{fileName}_MockMembers.g.cs", membersSource);

        if (model.Events.Length > 0)
        {
            var eventsSource = MockEventsBuilder.Build(model);
            spc.AddSource($"{fileName}_MockEvents.g.cs", eventsSource);
        }
    }

    private static string BuildCombinedImplAndFactory(MockTypeModel model)
    {
        var writer = new CodeWriter();
        var mockNamespace = MockImplBuilder.GetMockNamespace(model);

        writer.AppendLine("// <auto-generated/>");
        writer.AppendLine("#nullable enable");
        writer.AppendLine();

        using (writer.Block($"namespace {mockNamespace}"))
        {
            MockImplBuilder.BuildInto(writer, model);
            writer.AppendLine();
            MockFactoryBuilder.BuildInto(writer, model);
        }

        return writer.ToString();
    }

    private static string GetSafeFileName(MockTypeModel model)
        => MockImplBuilder.GetCompositeSafeName(model);
}
