using System.Collections;
using System.Diagnostics.CodeAnalysis;
using System.Linq.Expressions;
using System.Runtime.CompilerServices;
using System.Text.RegularExpressions;
using TUnit.Assertions.Chaining;
using TUnit.Assertions.Conditions;
using TUnit.Assertions.Conditions.Wrappers;
using TUnit.Assertions.Core;
using TUnit.Assertions.Sources;

namespace TUnit.Assertions.Extensions;

/// <summary>
/// Extension methods for IAssertionSource&lt;T&gt; - the primary assertion API surface.
/// These methods work on Assertion&lt;T&gt;, AndContinuation&lt;T&gt;, and OrContinuation&lt;T&gt;!
/// No duplication needed - one set of extensions for everything!
/// </summary>
public static class AssertionExtensions
{
    // ============ NULL CHECKS ============
    // IsNull and IsNotNull are now generated by AssertionExtensionGenerator

    // ============ EQUALITY ============

    /// <summary>
    /// Asserts that the value is equal to the expected value.
    /// Generic method that works for all types.
    /// Priority 0: Fallback for types without specialized overloads.
    /// </summary>
    [OverloadResolutionPriority(0)]
    public static EqualsAssertion<TValue> IsEqualTo<TValue>(
        this IAssertionSource<TValue> source,
        TValue expected,
        [CallerArgumentExpression(nameof(expected))] string? expression = null)
    {
        source.Context.ExpressionBuilder.Append($".IsEqualTo({expression})");
        return new EqualsAssertion<TValue>(source.Context, expected);
    }

    /// <summary>
    /// Alias for IsEqualTo - asserts that the value is equal to the expected value.
    /// Works with assertions, And, and Or continuations!
    /// </summary>
    public static EqualsAssertion<TValue> EqualTo<TValue>(
        this IAssertionSource<TValue> source,
        TValue expected,
        [CallerArgumentExpression(nameof(expected))] string? expression = null)
    {
        source.Context.ExpressionBuilder.Append($".EqualTo({expression})");
        return new EqualsAssertion<TValue>(source.Context, expected);
    }

    // IsNotEqualTo<TValue> is now generated by AssertionExtensionGenerator

    /// <summary>
    /// Asserts that the DateTime is equal to the expected value.
    /// Returns DateTimeEqualsAssertion which has .Within() method!
    /// Priority 2: Highest priority for specialized type.
    /// </summary>
    [OverloadResolutionPriority(2)]
    public static DateTimeEqualsAssertion IsEqualTo(
        this IAssertionSource<DateTime> source,
        DateTime expected,
        [CallerArgumentExpression(nameof(expected))] string? expression = null)
    {
        source.Context.ExpressionBuilder.Append($".IsEqualTo({expression})");
        return new DateTimeEqualsAssertion(source.Context, expected);
    }

    /// <summary>
    /// Asserts that the string is equal to the expected value.
    /// Returns StringEqualsAssertion which has .IgnoringCase() and .WithComparison() methods!
    /// Priority 2: Highest priority for specialized type.
    /// </summary>
    [OverloadResolutionPriority(2)]
    public static StringEqualsAssertion IsEqualTo(
        this IAssertionSource<string> source,
        string? expected,
        [CallerArgumentExpression(nameof(expected))] string? expression = null)
    {
        source.Context.ExpressionBuilder.Append($".IsEqualTo({expression})");
        return new StringEqualsAssertion(source.Context, expected);
    }

    /// <summary>
    /// Asserts that the string is equal to the expected value using the specified comparison.
    /// </summary>
    public static StringEqualsAssertion IsEqualTo(
        this IAssertionSource<string> source,
        string? expected,
        StringComparison comparison,
        [CallerArgumentExpression(nameof(expected))] string? expression = null)
    {
        source.Context.ExpressionBuilder.Append($".IsEqualTo({expression}, {comparison})");
        var assertion = new StringEqualsAssertion(source.Context, expected);
        return assertion.WithComparison(comparison);
    }

#if NET6_0_OR_GREATER
    /// <summary>
    /// Asserts that the DateOnly is equal to the expected value.
    /// Returns DateOnlyEqualsAssertion which has .WithinDays() method!
    /// Priority 2: Highest priority for specialized type.
    /// </summary>
    [OverloadResolutionPriority(2)]
    public static DateOnlyEqualsAssertion IsEqualTo(
        this IAssertionSource<DateOnly> source,
        DateOnly expected,
        [CallerArgumentExpression(nameof(expected))] string? expression = null)
    {
        source.Context.ExpressionBuilder.Append($".IsEqualTo({expression})");
        return new DateOnlyEqualsAssertion(source.Context, expected);
    }

    /// <summary>
    /// Asserts that the TimeOnly is equal to the expected value.
    /// Returns TimeOnlyEqualsAssertion which has .Within() method!
    /// Priority 2: Highest priority for specialized type.
    /// </summary>
    [OverloadResolutionPriority(2)]
    public static TimeOnlyEqualsAssertion IsEqualTo(
        this IAssertionSource<TimeOnly> source,
        TimeOnly expected,
        [CallerArgumentExpression(nameof(expected))] string? expression = null)
    {
        source.Context.ExpressionBuilder.Append($".IsEqualTo({expression})");
        return new TimeOnlyEqualsAssertion(source.Context, expected);
    }
#endif

    /// <summary>
    /// Asserts that the double is equal to the expected value.
    /// Returns DoubleEqualsAssertion which has .Within() method!
    /// Priority 2: Highest priority for specialized type.
    /// </summary>
    [OverloadResolutionPriority(2)]
    public static DoubleEqualsAssertion IsEqualTo(
        this IAssertionSource<double> source,
        double expected,
        [CallerArgumentExpression(nameof(expected))] string? expression = null)
    {
        source.Context.ExpressionBuilder.Append($".IsEqualTo({expression})");
        return new DoubleEqualsAssertion(source.Context, expected);
    }

    /// <summary>
    /// Asserts that the float is equal to the expected value.
    /// Returns FloatEqualsAssertion which has .Within() method!
    /// Priority 2: Highest priority for specialized type.
    /// </summary>
    [OverloadResolutionPriority(2)]
    public static FloatEqualsAssertion IsEqualTo(
        this IAssertionSource<float> source,
        float expected,
        [CallerArgumentExpression(nameof(expected))] string? expression = null)
    {
        source.Context.ExpressionBuilder.Append($".IsEqualTo({expression})");
        return new FloatEqualsAssertion(source.Context, expected);
    }

    /// <summary>
    /// Asserts that the long is equal to the expected value.
    /// Returns LongEqualsAssertion which has .Within() method!
    /// Priority 2: Highest priority for specialized type.
    /// </summary>
    [OverloadResolutionPriority(2)]
    public static LongEqualsAssertion IsEqualTo(
        this IAssertionSource<long> source,
        long expected,
        [CallerArgumentExpression(nameof(expected))] string? expression = null)
    {
        source.Context.ExpressionBuilder.Append($".IsEqualTo({expression})");
        return new LongEqualsAssertion(source.Context, expected);
    }

    /// <summary>
    /// Asserts that the DateTimeOffset is equal to the expected value.
    /// Returns DateTimeOffsetEqualsAssertion which has .Within() method!
    /// Priority 2: Highest priority for specialized type.
    /// </summary>
    [OverloadResolutionPriority(2)]
    public static DateTimeOffsetEqualsAssertion IsEqualTo(
        this IAssertionSource<DateTimeOffset> source,
        DateTimeOffset expected,
        [CallerArgumentExpression(nameof(expected))] string? expression = null)
    {
        source.Context.ExpressionBuilder.Append($".IsEqualTo({expression})");
        return new DateTimeOffsetEqualsAssertion(source.Context, expected);
    }

    /// <summary>
    /// Asserts that the int is equal to the expected value.
    /// Priority 2: Takes precedence over IEquatable overload to provide .Within() support.
    /// </summary>
    [OverloadResolutionPriority(2)]
    public static EqualsAssertion<int> IsEqualTo(
        this IAssertionSource<int> source,
        int expected,
        [CallerArgumentExpression(nameof(expected))] string? expression = null)
    {
        source.Context.ExpressionBuilder.Append($".IsEqualTo({expression})");
        return new EqualsAssertion<int>(source.Context, expected);
    }

    /// <summary>
    /// Asserts that the TimeSpan is equal to the expected value.
    /// Priority 2: Takes precedence over IEquatable overload to provide .Within() support.
    /// </summary>
    [OverloadResolutionPriority(2)]
    public static EqualsAssertion<TimeSpan> IsEqualTo(
        this IAssertionSource<TimeSpan> source,
        TimeSpan expected,
        [CallerArgumentExpression(nameof(expected))] string? expression = null)
    {
        source.Context.ExpressionBuilder.Append($".IsEqualTo({expression})");
        return new EqualsAssertion<TimeSpan>(source.Context, expected);
    }

    /// <summary>
    /// Asserts that a struct implementing IEquatable&lt;TExpected&gt; is equal to the expected value.
    /// This enables direct equality comparisons for structs with cross-type IEquatable implementations.
    /// Example: A Wrapper struct implementing IEquatable&lt;long&gt; can be compared directly to a long value.
    /// Priority -1: Lower than generic fallback; only used for cross-type IEquatable scenarios (TActual != TExpected).
    /// </summary>
    [OverloadResolutionPriority(-1)]
    public static EquatableAssertion<TActual, TExpected> IsEqualTo<TActual, TExpected>(
        this IAssertionSource<TActual> source,
        TExpected expected,
        [CallerArgumentExpression(nameof(expected))] string? expression = null)
        where TActual : struct, IEquatable<TExpected>
    {
        source.Context.ExpressionBuilder.Append($".IsEqualTo({expression})");
        return new EquatableAssertion<TActual, TExpected>(source.Context, expected);
    }

    /// <summary>
    /// Asserts that a nullable struct implementing IEquatable&lt;TExpected&gt; is equal to the expected value.
    /// Handles nullable structs with cross-type IEquatable implementations.
    /// Priority -1: Lower than generic fallback; only used for cross-type IEquatable scenarios (TActual != TExpected).
    /// </summary>
    [OverloadResolutionPriority(-1)]
    public static NullableEquatableAssertion<TActual, TExpected> IsEqualTo<TActual, TExpected>(
        this IAssertionSource<TActual?> source,
        TExpected expected,
        [CallerArgumentExpression(nameof(expected))] string? expression = null)
        where TActual : struct, IEquatable<TExpected>
    {
        source.Context.ExpressionBuilder.Append($".IsEqualTo({expression})");
        return new NullableEquatableAssertion<TActual, TExpected>(source.Context, expected);
    }

    // ============ COMPARISONS ============
    // IsGreaterThan, IsGreaterThanOrEqualTo, IsLessThan, IsLessThanOrEqualTo, and IsBetween
    // are now generated by AssertionExtensionGenerator

    /// <summary>
    /// Asserts that the numeric value is greater than zero (positive).
    /// </summary>
    public static GreaterThanAssertion<TValue> IsPositive<TValue>(
        this IAssertionSource<TValue> source)
        where TValue : IComparable<TValue>
    {
        source.Context.ExpressionBuilder.Append(".IsPositive()");
        return new GreaterThanAssertion<TValue>(source.Context, default(TValue)!);
    }

    /// <summary>
    /// Asserts that the nullable numeric value is greater than zero (positive).
    /// </summary>
    public static GreaterThanAssertion<TValue> IsPositive<TValue>(
        this IAssertionSource<TValue?> source)
        where TValue : struct, IComparable<TValue>
    {
        source.Context.ExpressionBuilder.Append(".IsPositive()");
        var mappedContext = source.Context.Map<TValue>(nullableValue =>
        {
            if (!nullableValue.HasValue)
            {
                throw new ArgumentNullException(nameof(nullableValue), "value was null");
            }

            return nullableValue.Value;
        });
        return new GreaterThanAssertion<TValue>(mappedContext, default(TValue)!);
    }

    /// <summary>
    /// Asserts that the numeric value is less than zero (negative).
    /// </summary>
    public static LessThanAssertion<TValue> IsNegative<TValue>(
        this IAssertionSource<TValue> source)
        where TValue : IComparable<TValue>
    {
        source.Context.ExpressionBuilder.Append(".IsNegative()");
        return new LessThanAssertion<TValue>(source.Context, default(TValue)!);
    }

    /// <summary>
    /// Asserts that the nullable numeric value is less than zero (negative).
    /// </summary>
    public static LessThanAssertion<TValue> IsNegative<TValue>(
        this IAssertionSource<TValue?> source)
        where TValue : struct, IComparable<TValue>
    {
        source.Context.ExpressionBuilder.Append(".IsNegative()");
        var mappedContext = source.Context.Map<TValue>(nullableValue =>
        {
            if (!nullableValue.HasValue)
            {
                throw new ArgumentNullException(nameof(nullableValue), "value was null");
            }

            return nullableValue.Value;
        });
        return new LessThanAssertion<TValue>(mappedContext, default(TValue)!);
    }

    // ============ BOOLEAN ============
    // IsTrue and IsFalse are now generated by AssertionExtensionGenerator for IAssertionSource<bool>

    // ============ TYPE CHECKS ============
    // IsTypeOf(Type), IsAssignableTo, IsNotAssignableTo are now generated by AssertionExtensionGenerator

    /// <summary>
    /// Asserts that the value is of the specified type and returns an assertion on the casted value.
    /// Example: await Assert.That(obj).IsTypeOf<StringBuilder>();
    /// Single type parameter version - infers source type.
    /// </summary>
    public static TypeOfAssertion<TValue, TExpected> IsTypeOf<TExpected, TValue>(
        this IAssertionSource<TValue> source)
    {
        source.Context.ExpressionBuilder.Append($".IsTypeOf<{typeof(TExpected).Name}>()");
        return new TypeOfAssertion<TValue, TExpected>(source.Context);
    }

    /// <summary>
    /// Asserts that the IEnumerable is of the specified type and returns an assertion on the casted value.
    /// Specialized overload for IEnumerable assertions with better type inference.
    /// Example: await Assert.That(enumerable).IsTypeOf<int[]>() where enumerable is IEnumerable<int>
    /// </summary>
    public static TypeOfAssertion<IEnumerable<TItem>, TExpected> IsTypeOf<TExpected, TItem>(
        this IAssertionSource<IEnumerable<TItem>> source)
    {
        source.Context.ExpressionBuilder.Append($".IsTypeOf<{typeof(TExpected).Name}>()");
        return new TypeOfAssertion<IEnumerable<TItem>, TExpected>(source.Context);
    }

    /// <summary>
    /// Asserts that the value is of the specified type (runtime Type parameter).
    /// Example: await Assert.That(obj).IsOfType(typeof(string));
    /// </summary>
    public static IsTypeOfRuntimeAssertion<TValue> IsOfType<TValue>(
        this IAssertionSource<TValue> source,
        Type expectedType,
        [CallerArgumentExpression(nameof(expectedType))] string? expression = null)
    {
        source.Context.ExpressionBuilder.Append($".IsOfType({expression})");
        return new IsTypeOfRuntimeAssertion<TValue>(source.Context, expectedType);
    }

    /// <summary>
    /// Asserts on a member of an object using a lambda selector and assertion lambda.
    /// The assertion lambda receives the member value and can perform any assertions on it.
    /// After the member assertion completes, returns to the parent object context for further chaining.
    /// Example: await Assert.That(myObject).Member(x => x.PropertyName, value => value.IsEqualTo(expectedValue));
    /// </summary>
    public static MemberAssertionResult<TObject> Member<TObject, TMember>(
        this IAssertionSource<TObject> source,
        Expression<Func<TObject, TMember>> memberSelector,
        Func<IAssertionSource<TMember>, Assertion<TMember>> assertions)
    {
        var parentContext = source.Context;
        var memberPath = GetMemberPath(memberSelector);

        parentContext.ExpressionBuilder.Append($".Member(x => x.{memberPath}, ...)");

        // Check if there's a pending link (from .And or .Or) that needs to be consumed
        var (pendingAssertion, combinerType) = parentContext.ConsumePendingLink();

        // Map to member context
        var memberContext = parentContext.Map<TMember>(obj =>
        {
            if (obj == null)
            {
                throw new InvalidOperationException($"Object `{typeof(TObject).Name}` was null");
            }

            var compiled = memberSelector.Compile();
            return compiled(obj);
        });

        // Let user build assertion via lambda
        // Create a simple adapter that implements IAssertionSource<TMember>
        var memberSource = new AssertionSourceAdapter<TMember>(memberContext);
        var memberAssertion = assertions(memberSource);

        // Type-erase to object? for storage
        var erasedAssertion = new TypeErasedAssertion<TMember>(memberAssertion);

        // If there was a pending link, wrap both assertions together
        if (pendingAssertion != null && combinerType != null)
        {
            // Create a combined wrapper that executes the pending assertion first (or together for Or)
            Assertion<object?> combinedAssertion = combinerType == CombinerType.And
                ? new CombinedAndAssertion<TObject>(parentContext, pendingAssertion, erasedAssertion)
                : new CombinedOrAssertion<TObject>(parentContext, pendingAssertion, erasedAssertion);

            return new MemberAssertionResult<TObject>(parentContext, combinedAssertion);
        }

        return new MemberAssertionResult<TObject>(parentContext, erasedAssertion);
    }

    /// <summary>
    /// Asserts on a member of an object using a lambda selector and assertion lambda.
    /// The assertion lambda receives the member value and can perform any assertions on it.
    /// After the member assertion completes, returns to the parent object context for further chaining.
    /// Example: await Assert.That(myObject).Member(x => x.Tags, tags => tags.Contains("value"));
    /// </summary>
    public static MemberAssertionResult<TObject> Member<TObject, TMember>(
        this IAssertionSource<TObject> source,
        Expression<Func<TObject, TMember>> memberSelector,
        Func<IAssertionSource<TMember>, object> assertions)
    {
        var parentContext = source.Context;
        var memberPath = GetMemberPath(memberSelector);

        parentContext.ExpressionBuilder.Append($".Member(x => x.{memberPath}, ...)");

        // Check if there's a pending link (from .And or .Or) that needs to be consumed
        var (pendingAssertion, combinerType) = parentContext.ConsumePendingLink();

        // Map to member context
        var memberContext = parentContext.Map<TMember>(obj =>
        {
            if (obj == null)
            {
                throw new InvalidOperationException($"Object `{typeof(TObject).Name}` was null");
            }

            var compiled = memberSelector.Compile();
            return compiled(obj);
        });

        // Let user build assertion via lambda
        var memberSource = new AssertionSourceAdapter<TMember>(memberContext);
        var memberAssertionObj = assertions(memberSource);

        // Type-erase to object? for storage
        var erasedAssertion = WrapMemberAssertion<TMember>(memberAssertionObj);

        // If there was a pending link, wrap both assertions together
        if (pendingAssertion != null && combinerType != null)
        {
            Assertion<object?> combinedAssertion = combinerType == CombinerType.And
                ? new CombinedAndAssertion<TObject>(parentContext, pendingAssertion, erasedAssertion)
                : new CombinedOrAssertion<TObject>(parentContext, pendingAssertion, erasedAssertion);

            return new MemberAssertionResult<TObject>(parentContext, combinedAssertion);
        }

        return new MemberAssertionResult<TObject>(parentContext, erasedAssertion);
    }

    /// <summary>
    /// Helper method to wrap member assertions for type erasure.
    /// </summary>
    private static Assertion<object?> WrapMemberAssertion<TMember>(object memberAssertion)
    {
        if (memberAssertion is Assertion<TMember> standardAssertion)
        {
            return new TypeErasedAssertion<TMember>(standardAssertion);
        }

        throw new InvalidOperationException(
            $"Member assertion returned unexpected type: {memberAssertion.GetType()}. " +
            $"Expected Assertion<{typeof(TMember).Name}>.");
    }

    private static string GetMemberPath<TObject, TMember>(Expression<Func<TObject, TMember>> expression)
    {
        var body = expression.Body;
        var parts = new List<string>();

        while (body is MemberExpression memberExpr)
        {
            parts.Insert(0, memberExpr.Member.Name);
            body = memberExpr.Expression;
        }

        return parts.Count > 0 ? string.Join(".", parts) : "Unknown";
    }

    // ============ REFERENCE EQUALITY ============
    // IsSameReferenceAs and IsNotSameReferenceAs are now generated by AssertionExtensionGenerator

    // ============ STRING ASSERTIONS ============
    // All string-specific assertion methods are now generated by AssertionExtensionGenerator
    // from their respective assertion classes (StringContainsAssertion, StringStartsWithAssertion, etc.)

    /// <summary>
    /// Returns a wrapper for string length assertions.
    /// Example: await Assert.That(str).HasLength().EqualTo(5);
    /// </summary>
    public static LengthWrapper HasLength(
        this IAssertionSource<string> source)
    {
        source.Context.ExpressionBuilder.Append(".HasLength()");
        return new LengthWrapper(source.Context);
    }

    /// <summary>
    /// Asserts that the string has the expected length.
    /// Example: await Assert.That(str).HasLength(5);
    /// </summary>
    public static StringLengthAssertion HasLength(
        this IAssertionSource<string> source,
        int expectedLength,
        [CallerArgumentExpression(nameof(expectedLength))] string? expression = null)
    {
        source.Context.ExpressionBuilder.Append($".HasLength({expression})");
        return new StringLengthAssertion(source.Context, expectedLength);
    }

    // ============ DICTIONARY ASSERTIONS ============

    /// <summary>
    /// Asserts that the dictionary contains the specified key.
    /// Example: await Assert.That(dict).ContainsKey("key");
    /// </summary>
    public static DictionaryContainsKeyAssertion<TKey, TValue> ContainsKey<TKey, TValue>(
        this IAssertionSource<IReadOnlyDictionary<TKey, TValue>> source,
        TKey key,
        [CallerArgumentExpression(nameof(key))] string? expression = null)
    {
        source.Context.ExpressionBuilder.Append($".ContainsKey({expression})");
        return new DictionaryContainsKeyAssertion<TKey, TValue>(source.Context, key);
    }

    /// <summary>
    /// Asserts that the dictionary contains the specified key.
    /// This overload works with custom dictionary types.
    /// Example: await Assert.That(customDict).ContainsKey("key");
    /// </summary>
    public static DictionaryContainsKeyAssertion<TKey, TValue> ContainsKey<TDictionary, TKey, TValue>(
        this IAssertionSource<TDictionary> source,
        TKey key,
        [CallerArgumentExpression(nameof(key))] string? expression = null)
        where TDictionary : IReadOnlyDictionary<TKey, TValue>
    {
        source.Context.ExpressionBuilder.Append($".ContainsKey({expression})");
        var mappedContext = source.Context.Map<IReadOnlyDictionary<TKey, TValue>>(dict => dict);
        return new DictionaryContainsKeyAssertion<TKey, TValue>(mappedContext, key);
    }

    /// <summary>
    /// Asserts that the dictionary contains the specified key using the specified comparer.
    /// Example: await Assert.That(dict).ContainsKey("key", StringComparer.OrdinalIgnoreCase);
    /// </summary>
    public static DictionaryContainsKeyAssertion<TKey, TValue> ContainsKey<TKey, TValue>(
        this IAssertionSource<IReadOnlyDictionary<TKey, TValue>> source,
        TKey key,
        IEqualityComparer<TKey> comparer,
        [CallerArgumentExpression(nameof(key))] string? expression = null)
    {
        source.Context.ExpressionBuilder.Append($".ContainsKey({expression}, comparer)");
        return new DictionaryContainsKeyAssertion<TKey, TValue>(source.Context, key,  comparer);
    }

    /// <summary>
    /// Asserts that the dictionary contains the specified key using the specified comparer.
    /// This overload works with custom dictionary types.
    /// </summary>
    public static DictionaryContainsKeyAssertion<TKey, TValue> ContainsKey<TDictionary, TKey, TValue>(
        this IAssertionSource<TDictionary> source,
        TKey key,
        IEqualityComparer<TKey> comparer,
        [CallerArgumentExpression(nameof(key))] string? expression = null)
        where TDictionary : IReadOnlyDictionary<TKey, TValue>
    {
        source.Context.ExpressionBuilder.Append($".ContainsKey({expression}, comparer)");
        var mappedContext = source.Context.Map<IReadOnlyDictionary<TKey, TValue>>(dict => dict);
        return new DictionaryContainsKeyAssertion<TKey, TValue>(mappedContext, key,  comparer);
    }

    /// <summary>
    /// Asserts that the dictionary does NOT contain the specified key.
    /// Example: await Assert.That(dict).DoesNotContainKey("key");
    /// </summary>
    public static DictionaryDoesNotContainKeyAssertion<TKey, TValue> DoesNotContainKey<TKey, TValue>(
        this IAssertionSource<IReadOnlyDictionary<TKey, TValue>> source,
        TKey key,
        [CallerArgumentExpression(nameof(key))] string? expression = null)
    {
        source.Context.ExpressionBuilder.Append($".DoesNotContainKey({expression})");
        return new DictionaryDoesNotContainKeyAssertion<TKey, TValue>(source.Context, key);
    }

    /// <summary>
    /// Asserts that the dictionary does NOT contain the specified key.
    /// This overload works with custom dictionary types.
    /// Example: await Assert.That(customDict).DoesNotContainKey("key");
    /// </summary>
    public static DictionaryDoesNotContainKeyAssertion<TKey, TValue> DoesNotContainKey<TDictionary, TKey, TValue>(
        this IAssertionSource<TDictionary> source,
        TKey key,
        [CallerArgumentExpression(nameof(key))] string? expression = null)
        where TDictionary : IReadOnlyDictionary<TKey, TValue>
    {
        source.Context.ExpressionBuilder.Append($".DoesNotContainKey({expression})");
        var mappedContext = source.Context.Map<IReadOnlyDictionary<TKey, TValue>>(dict => dict);
        return new DictionaryDoesNotContainKeyAssertion<TKey, TValue>(mappedContext, key);
    }

    // ============ COLLECTION ASSERTIONS ============

    /// <summary>
    /// Asserts that the collection is empty.
    /// </summary>
    public static CollectionIsEmptyAssertion<TValue> IsEmpty<TValue>(
        this IAssertionSource<TValue> source)
        where TValue : IEnumerable
    {
        source.Context.ExpressionBuilder.Append(".IsEmpty()");
        return new CollectionIsEmptyAssertion<TValue>(source.Context);
    }

    /// <summary>
    /// Asserts that the collection is NOT empty.
    /// </summary>
    public static CollectionIsNotEmptyAssertion<TValue> IsNotEmpty<TValue>(
        this IAssertionSource<TValue> source)
        where TValue : IEnumerable
    {
        source.Context.ExpressionBuilder.Append(".IsNotEmpty()");
        return new CollectionIsNotEmptyAssertion<TValue>(source.Context);
    }

    /// <summary>
    /// Asserts that the collection contains the expected item.
    /// </summary>
    public static CollectionContainsAssertion<TCollection, TItem> Contains<TCollection, TItem>(
        this IAssertionSource<TCollection> source,
        TItem expected,
        [CallerArgumentExpression(nameof(expected))] string? expression = null)
        where TCollection : IEnumerable<TItem>
    {
        source.Context.ExpressionBuilder.Append($".Contains({expression})");
        return new CollectionContainsAssertion<TCollection, TItem>(source.Context, expected);
    }

    /// <summary>
    /// Asserts that the collection contains an item matching the predicate.
    /// </summary>
    public static CollectionContainsPredicateAssertion<TCollection, TItem> Contains<TCollection, TItem>(
        this IAssertionSource<TCollection> source,
        Func<TItem, bool> predicate,
        [CallerArgumentExpression(nameof(predicate))] string? expression = null)
        where TCollection : IEnumerable<TItem>
    {
        source.Context.ExpressionBuilder.Append($".Contains({expression})");
        return new CollectionContainsPredicateAssertion<TCollection, TItem>(source.Context, predicate);
    }

    /// <summary>
    /// Asserts that the collection contains the expected item.
    /// Specific overload for IEnumerable to fix C# type inference.
    /// </summary>
    public static CollectionContainsAssertion<IEnumerable<TItem>, TItem> Contains<TItem>(
        this IAssertionSource<IEnumerable<TItem>> source,
        TItem expected,
        [CallerArgumentExpression(nameof(expected))] string? expression = null)
    {
        source.Context.ExpressionBuilder.Append($".Contains({expression})");
        return new CollectionContainsAssertion<IEnumerable<TItem>, TItem>(source.Context, expected);
    }

    /// <summary>
    /// Asserts that the collection contains an item matching the predicate.
    /// Specific overload for IEnumerable to fix C# type inference.
    /// </summary>
    public static CollectionContainsPredicateAssertion<IEnumerable<TItem>, TItem> Contains<TItem>(
        this IAssertionSource<IEnumerable<TItem>> source,
        Func<TItem, bool> predicate,
        [CallerArgumentExpression(nameof(predicate))] string? expression = null)
    {
        source.Context.ExpressionBuilder.Append($".Contains({expression})");
        return new CollectionContainsPredicateAssertion<IEnumerable<TItem>, TItem>(source.Context, predicate);
    }


    /// <summary>
    /// Asserts that the collection does NOT contain the expected item.
    /// </summary>
    public static CollectionDoesNotContainAssertion<TCollection, TItem> DoesNotContain<TCollection, TItem>(
        this IAssertionSource<TCollection> source,
        TItem expected,
        [CallerArgumentExpression(nameof(expected))] string? expression = null)
        where TCollection : IEnumerable<TItem>
    {
        source.Context.ExpressionBuilder.Append($".DoesNotContain({expression})");
        return new CollectionDoesNotContainAssertion<TCollection, TItem>(source.Context, expected);
    }

    /// <summary>
    /// Asserts that the collection does NOT contain any item matching the predicate.
    /// </summary>
    public static CollectionDoesNotContainPredicateAssertion<TCollection, TItem> DoesNotContain<TCollection, TItem>(
        this IAssertionSource<TCollection> source,
        Func<TItem, bool> predicate,
        [CallerArgumentExpression(nameof(predicate))] string? expression = null)
        where TCollection : IEnumerable<TItem>
    {
        source.Context.ExpressionBuilder.Append($".DoesNotContain({expression})");
        return new CollectionDoesNotContainPredicateAssertion<TCollection, TItem>(source.Context, predicate, expression ?? "predicate");
    }

    /// <summary>
    /// Asserts that the collection does NOT contain the expected item.
    /// Specific overload for IEnumerable to fix C# type inference.
    /// </summary>
    public static CollectionDoesNotContainAssertion<IEnumerable<TItem>, TItem> DoesNotContain<TItem>(
        this IAssertionSource<IEnumerable<TItem>> source,
        TItem expected,
        [CallerArgumentExpression(nameof(expected))] string? expression = null)
    {
        source.Context.ExpressionBuilder.Append($".DoesNotContain({expression})");
        return new CollectionDoesNotContainAssertion<IEnumerable<TItem>, TItem>(source.Context, expected);
    }

    /// <summary>
    /// Asserts that the collection does NOT contain any item matching the predicate.
    /// Specific overload for IEnumerable to fix C# type inference.
    /// </summary>
    public static CollectionDoesNotContainPredicateAssertion<IEnumerable<TItem>, TItem> DoesNotContain<TItem>(
        this IAssertionSource<IEnumerable<TItem>> source,
        Func<TItem, bool> predicate,
        [CallerArgumentExpression(nameof(predicate))] string? expression = null)
    {
        source.Context.ExpressionBuilder.Append($".DoesNotContain({expression})");
        return new CollectionDoesNotContainPredicateAssertion<IEnumerable<TItem>, TItem>(source.Context, predicate, expression ?? "predicate");
    }

    /// <summary>
    /// Asserts that the collection contains ONLY items matching the predicate (all items satisfy the predicate).
    /// </summary>
    public static CollectionAllAssertion<TCollection, TItem> ContainsOnly<TCollection, TItem>(
        this IAssertionSource<TCollection> source,
        Func<TItem, bool> predicate,
        [CallerArgumentExpression(nameof(predicate))] string? expression = null)
        where TCollection : IEnumerable<TItem>
    {
        source.Context.ExpressionBuilder.Append($".ContainsOnly({expression})");
        return new CollectionAllAssertion<TCollection, TItem>(source.Context, predicate, expression ?? "predicate");
    }

    /// <summary>
    /// Asserts that the collection contains ONLY items matching the predicate (all items satisfy the predicate).
    /// Specific overload for IEnumerable to fix C# type inference.
    /// </summary>
    public static CollectionAllAssertion<IEnumerable<TItem>, TItem> ContainsOnly<TItem>(
        this IAssertionSource<IEnumerable<TItem>> source,
        Func<TItem, bool> predicate,
        [CallerArgumentExpression(nameof(predicate))] string? expression = null)
    {
        source.Context.ExpressionBuilder.Append($".ContainsOnly({expression})");
        return new CollectionAllAssertion<IEnumerable<TItem>, TItem>(source.Context, predicate, expression ?? "predicate");
    }

    /// <summary>
    /// Asserts that the collection is in ascending order.
    /// </summary>
    public static CollectionIsInOrderAssertion<TCollection, TItem> IsInOrder<TCollection, TItem>(
        this IAssertionSource<TCollection> source)
        where TCollection : IEnumerable<TItem>
        where TItem : IComparable<TItem>
    {
        source.Context.ExpressionBuilder.Append(".IsInOrder()");
        return new CollectionIsInOrderAssertion<TCollection, TItem>(source.Context);
    }

    /// <summary>
    /// Asserts that the collection is in ascending order.
    /// Optimized overload for CollectionAssertionBase with better type inference.
    /// </summary>
    public static CollectionIsInOrderAssertion<TCollection, TItem> IsInOrder<TCollection, TItem>(
        this Sources.CollectionAssertionBase<TCollection, TItem> source)
        where TCollection : IEnumerable<TItem>
        where TItem : IComparable<TItem>
    {
        var context = ((IAssertionSource<TCollection>)source).Context;
        context.ExpressionBuilder.Append(".IsInOrder()");
        return new CollectionIsInOrderAssertion<TCollection, TItem>(context);
    }

    /// <summary>
    /// Asserts that the collection is in ascending order.
    /// Specific overload for IEnumerable to fix C# type inference.
    /// </summary>
    public static CollectionIsInOrderAssertion<IEnumerable<TItem>, TItem> IsInOrder<TItem>(
        this IAssertionSource<IEnumerable<TItem>> source)
        where TItem : IComparable<TItem>
    {
        source.Context.ExpressionBuilder.Append(".IsInOrder()");
        return new CollectionIsInOrderAssertion<IEnumerable<TItem>, TItem>(source.Context);
    }

    /// <summary>
    /// Asserts that the collection is in descending order.
    /// </summary>
    public static CollectionIsInDescendingOrderAssertion<TCollection, TItem> IsInDescendingOrder<TCollection, TItem>(
        this IAssertionSource<TCollection> source)
        where TCollection : IEnumerable<TItem>
        where TItem : IComparable<TItem>
    {
        source.Context.ExpressionBuilder.Append(".IsInDescendingOrder()");
        return new CollectionIsInDescendingOrderAssertion<TCollection, TItem>(source.Context);
    }

    /// <summary>
    /// Asserts that the collection is in descending order.
    /// Optimized overload for CollectionAssertionBase with better type inference.
    /// </summary>
    public static CollectionIsInDescendingOrderAssertion<TCollection, TItem> IsInDescendingOrder<TCollection, TItem>(
        this Sources.CollectionAssertionBase<TCollection, TItem> source)
        where TCollection : IEnumerable<TItem>
        where TItem : IComparable<TItem>
    {
        var context = ((IAssertionSource<TCollection>)source).Context;
        context.ExpressionBuilder.Append(".IsInDescendingOrder()");
        return new CollectionIsInDescendingOrderAssertion<TCollection, TItem>(context);
    }

    /// <summary>
    /// Asserts that the collection is in descending order.
    /// Specific overload for IEnumerable to fix C# type inference.
    /// </summary>
    public static CollectionIsInDescendingOrderAssertion<IEnumerable<TItem>, TItem> IsInDescendingOrder<TItem>(
        this IAssertionSource<IEnumerable<TItem>> source)
        where TItem : IComparable<TItem>
    {
        source.Context.ExpressionBuilder.Append(".IsInDescendingOrder()");
        return new CollectionIsInDescendingOrderAssertion<IEnumerable<TItem>, TItem>(source.Context);
    }

    /// <summary>
    /// Asserts that the collection is ordered by the specified key selector in ascending order.
    /// </summary>
    public static CollectionIsOrderedByAssertion<TCollection, TItem, TKey> IsOrderedBy<TCollection, TItem, TKey>(
        this IAssertionSource<TCollection> source,
        Func<TItem, TKey> keySelector,
        [CallerArgumentExpression(nameof(keySelector))] string? expression = null)
        where TCollection : IEnumerable<TItem>
    {
        source.Context.ExpressionBuilder.Append($".IsOrderedBy({expression})");
        return new CollectionIsOrderedByAssertion<TCollection, TItem, TKey>(source.Context, keySelector);
    }

    /// <summary>
    /// Asserts that the collection is ordered by the specified key selector in ascending order using the specified comparer.
    /// </summary>
    public static CollectionIsOrderedByAssertion<TCollection, TItem, TKey> IsOrderedBy<TCollection, TItem, TKey>(
        this IAssertionSource<TCollection> source,
        Func<TItem, TKey> keySelector,
        IComparer<TKey> comparer,
        [CallerArgumentExpression(nameof(keySelector))] string? expression = null)
        where TCollection : IEnumerable<TItem>
    {
        source.Context.ExpressionBuilder.Append($".IsOrderedBy({expression}, comparer)");
        return new CollectionIsOrderedByAssertion<TCollection, TItem, TKey>(source.Context, keySelector, comparer);
    }

    /// <summary>
    /// Asserts that the collection is ordered by the specified key selector in ascending order.
    /// Specific overload for IEnumerable to fix C# type inference.
    /// </summary>
    public static CollectionIsOrderedByAssertion<IEnumerable<TItem>, TItem, TKey> IsOrderedBy<TItem, TKey>(
        this IAssertionSource<IEnumerable<TItem>> source,
        Func<TItem, TKey> keySelector,
        [CallerArgumentExpression(nameof(keySelector))] string? expression = null)
    {
        source.Context.ExpressionBuilder.Append($".IsOrderedBy({expression})");
        return new CollectionIsOrderedByAssertion<IEnumerable<TItem>, TItem, TKey>(source.Context, keySelector);
    }

    /// <summary>
    /// Asserts that the collection is ordered by the specified key selector in ascending order using the specified comparer.
    /// Specific overload for IEnumerable to fix C# type inference.
    /// </summary>
    public static CollectionIsOrderedByAssertion<IEnumerable<TItem>, TItem, TKey> IsOrderedBy<TItem, TKey>(
        this IAssertionSource<IEnumerable<TItem>> source,
        Func<TItem, TKey> keySelector,
        IComparer<TKey> comparer,
        [CallerArgumentExpression(nameof(keySelector))] string? expression = null)
    {
        source.Context.ExpressionBuilder.Append($".IsOrderedBy({expression}, comparer)");
        return new CollectionIsOrderedByAssertion<IEnumerable<TItem>, TItem, TKey>(source.Context, keySelector, comparer);
    }

    /// <summary>
    /// Asserts that the collection is ordered by the specified key selector in descending order.
    /// </summary>
    public static CollectionIsOrderedByDescendingAssertion<TCollection, TItem, TKey> IsOrderedByDescending<TCollection, TItem, TKey>(
        this IAssertionSource<TCollection> source,
        Func<TItem, TKey> keySelector,
        [CallerArgumentExpression(nameof(keySelector))] string? expression = null)
        where TCollection : IEnumerable<TItem>
    {
        source.Context.ExpressionBuilder.Append($".IsOrderedByDescending({expression})");
        return new CollectionIsOrderedByDescendingAssertion<TCollection, TItem, TKey>(source.Context, keySelector);
    }

    /// <summary>
    /// Asserts that the collection is ordered by the specified key selector in descending order using the specified comparer.
    /// </summary>
    public static CollectionIsOrderedByDescendingAssertion<TCollection, TItem, TKey> IsOrderedByDescending<TCollection, TItem, TKey>(
        this IAssertionSource<TCollection> source,
        Func<TItem, TKey> keySelector,
        IComparer<TKey> comparer,
        [CallerArgumentExpression(nameof(keySelector))] string? expression = null)
        where TCollection : IEnumerable<TItem>
    {
        source.Context.ExpressionBuilder.Append($".IsOrderedByDescending({expression}, comparer)");
        return new CollectionIsOrderedByDescendingAssertion<TCollection, TItem, TKey>(source.Context, keySelector, comparer);
    }

    /// <summary>
    /// Asserts that the collection is ordered by the specified key selector in descending order.
    /// Specific overload for IEnumerable to fix C# type inference.
    /// </summary>
    public static CollectionIsOrderedByDescendingAssertion<IEnumerable<TItem>, TItem, TKey> IsOrderedByDescending<TItem, TKey>(
        this IAssertionSource<IEnumerable<TItem>> source,
        Func<TItem, TKey> keySelector,
        [CallerArgumentExpression(nameof(keySelector))] string? expression = null)
    {
        source.Context.ExpressionBuilder.Append($".IsOrderedByDescending({expression})");
        return new CollectionIsOrderedByDescendingAssertion<IEnumerable<TItem>, TItem, TKey>(source.Context, keySelector);
    }

    /// <summary>
    /// Asserts that the collection is ordered by the specified key selector in descending order using the specified comparer.
    /// Specific overload for IEnumerable to fix C# type inference.
    /// </summary>
    public static CollectionIsOrderedByDescendingAssertion<IEnumerable<TItem>, TItem, TKey> IsOrderedByDescending<TItem, TKey>(
        this IAssertionSource<IEnumerable<TItem>> source,
        Func<TItem, TKey> keySelector,
        IComparer<TKey> comparer,
        [CallerArgumentExpression(nameof(keySelector))] string? expression = null)
    {
        source.Context.ExpressionBuilder.Append($".IsOrderedByDescending({expression}, comparer)");
        return new CollectionIsOrderedByDescendingAssertion<IEnumerable<TItem>, TItem, TKey>(source.Context, keySelector, comparer);
    }

    /// <summary>
    /// Returns a wrapper for collection count assertions.
    /// Example: await Assert.That(list).HasCount().EqualTo(5);
    /// </summary>
    public static CountWrapper<TValue> HasCount<TValue>(
        this IAssertionSource<TValue> source)
        where TValue : IEnumerable
    {
        source.Context.ExpressionBuilder.Append(".HasCount()");
        return new CountWrapper<TValue>(source.Context);
    }

    /// <summary>
    /// Asserts that the collection has the expected count.
    /// Example: await Assert.That(list).HasCount(5);
    /// </summary>
    public static CollectionCountAssertion<TValue> HasCount<TValue>(
        this IAssertionSource<TValue> source,
        int expectedCount,
        [CallerArgumentExpression(nameof(expectedCount))] string? expression = null)
        where TValue : IEnumerable
    {
        source.Context.ExpressionBuilder.Append($".HasCount({expression})");
        return new CollectionCountAssertion<TValue>(source.Context, expectedCount);
    }

    /// <summary>
    /// Creates a helper for asserting that all items in the collection satisfy custom assertions.
    /// Example: await Assert.That(list).All().Satisfy(item => item.IsNotNull());
    /// </summary>
    public static CollectionAllSatisfyHelper<TCollection, TItem> All<TCollection, TItem>(
        this IAssertionSource<TCollection> source)
        where TCollection : IEnumerable<TItem>
    {
        source.Context.ExpressionBuilder.Append(".All()");
        return new CollectionAllSatisfyHelper<TCollection, TItem>(source.Context);
    }

    /// <summary>
    /// Asserts that all items in the collection satisfy the predicate.
    /// </summary>
    public static CollectionAllAssertion<TCollection, TItem> All<TCollection, TItem>(
        this IAssertionSource<TCollection> source,
        Func<TItem, bool> predicate,
        [CallerArgumentExpression(nameof(predicate))] string? expression = null)
        where TCollection : IEnumerable<TItem>
    {
        source.Context.ExpressionBuilder.Append($".All({expression})");
        return new CollectionAllAssertion<TCollection, TItem>(source.Context, predicate, expression ?? "predicate");
    }

    /// <summary>
    /// Creates a helper for asserting that all items in the collection satisfy custom assertions.
    /// Specific overload for IEnumerable to fix C# type inference.
    /// Example: await Assert.That(list).All().Satisfy(item => item.IsNotNull());
    /// </summary>
    public static CollectionAllSatisfyHelper<IEnumerable<TItem>, TItem> All<TItem>(
        this IAssertionSource<IEnumerable<TItem>> source)
    {
        source.Context.ExpressionBuilder.Append(".All()");
        return new CollectionAllSatisfyHelper<IEnumerable<TItem>, TItem>(source.Context);
    }

    /// <summary>
    /// Asserts that all items in the collection satisfy the predicate.
    /// Specific overload for IEnumerable to fix C# type inference.
    /// </summary>
    public static CollectionAllAssertion<IEnumerable<TItem>, TItem> All<TItem>(
        this IAssertionSource<IEnumerable<TItem>> source,
        Func<TItem, bool> predicate,
        [CallerArgumentExpression(nameof(predicate))] string? expression = null)
    {
        source.Context.ExpressionBuilder.Append($".All({expression})");
        return new CollectionAllAssertion<IEnumerable<TItem>, TItem>(source.Context, predicate, expression ?? "predicate");
    }

    /// <summary>
    /// Asserts that at least one item in the collection satisfies the predicate.
    /// </summary>
    public static CollectionAnyAssertion<TCollection, TItem> Any<TCollection, TItem>(
        this IAssertionSource<TCollection> source,
        Func<TItem, bool> predicate,
        [CallerArgumentExpression(nameof(predicate))] string? expression = null)
        where TCollection : IEnumerable<TItem>
    {
        source.Context.ExpressionBuilder.Append($".Any({expression})");
        return new CollectionAnyAssertion<TCollection, TItem>(source.Context, predicate, expression ?? "predicate");
    }

    /// <summary>
    /// Asserts that the collection contains exactly one item.
    /// </summary>
    public static HasSingleItemAssertion<TValue> HasSingleItem<TValue>(
        this IAssertionSource<TValue> source)
        where TValue : IEnumerable
    {
        source.Context.ExpressionBuilder.Append(".HasSingleItem()");
        return new HasSingleItemAssertion<TValue>(source.Context);
    }

    /// <summary>
    /// Asserts that the collection contains only distinct (unique) items.
    /// </summary>
    public static HasDistinctItemsAssertion<TValue> HasDistinctItems<TValue>(
        this IAssertionSource<TValue> source)
        where TValue : IEnumerable
    {
        source.Context.ExpressionBuilder.Append(".HasDistinctItems()");
        return new HasDistinctItemsAssertion<TValue>(source.Context);
    }

    /// <summary>
    /// Asserts that the collection is equivalent to the expected collection.
    /// Two collections are equivalent if they contain the same elements, regardless of order.
    /// </summary>
    public static IsEquivalentToAssertion<TCollection, TItem> IsEquivalentTo<TCollection, TItem>(
        this IAssertionSource<TCollection> source,
        IEnumerable<TItem> expected,
        [CallerArgumentExpression(nameof(expected))] string? expression = null)
        where TCollection : IEnumerable<TItem>
    {
        source.Context.ExpressionBuilder.Append($".IsEquivalentTo({expression})");
        return new IsEquivalentToAssertion<TCollection, TItem>(source.Context, expected);
    }

    /// <summary>
    /// Asserts that the collection is equivalent to the expected collection using the specified comparer.
    /// Two collections are equivalent if they contain the same elements, regardless of order.
    /// </summary>
    public static IsEquivalentToAssertion<TCollection, TItem> IsEquivalentTo<TCollection, TItem>(
        this IAssertionSource<TCollection> source,
        IEnumerable<TItem> expected,
        IEqualityComparer<TItem> comparer,
        [CallerArgumentExpression(nameof(expected))] string? expression = null)
        where TCollection : IEnumerable<TItem>
    {
        source.Context.ExpressionBuilder.Append($".IsEquivalentTo({expression}, comparer)");
        return new IsEquivalentToAssertion<TCollection, TItem>(source.Context, expected).Using(comparer);
    }

    /// <summary>
    /// Asserts that the collection is equivalent to the expected collection with the specified ordering requirement.
    /// </summary>
    public static IsEquivalentToAssertion<TCollection, TItem> IsEquivalentTo<TCollection, TItem>(
        this IAssertionSource<TCollection> source,
        IEnumerable<TItem> expected,
        Enums.CollectionOrdering ordering,
        [CallerArgumentExpression(nameof(expected))] string? expression = null)
        where TCollection : IEnumerable<TItem>
    {
        source.Context.ExpressionBuilder.Append($".IsEquivalentTo({expression}, CollectionOrdering.{ordering})");
        return new IsEquivalentToAssertion<TCollection, TItem>(source.Context, expected,  ordering);
    }

    /// <summary>
    /// Asserts that the value is structurally equivalent to the expected value.
    /// Performs deep comparison of properties and fields.
    /// Supports .WithPartialEquivalency() and .IgnoringMember() for advanced scenarios.
    /// </summary>
    public static StructuralEquivalencyAssertion<TValue> IsEquivalentTo<TValue>(
        this IAssertionSource<TValue> source,
        object? expected,
        [CallerArgumentExpression(nameof(expected))] string? expression = null)
    {
        source.Context.ExpressionBuilder.Append($".IsEquivalentTo({expression})");
        return new StructuralEquivalencyAssertion<TValue>(source.Context, expected, expression);
    }

    /// <summary>
    /// Asserts that the collection is NOT equivalent to the expected collection.
    /// Two collections are NOT equivalent if they differ in elements or order.
    /// </summary>
    public static NotEquivalentToAssertion<TCollection, TItem> IsNotEquivalentTo<TCollection, TItem>(
        this IAssertionSource<TCollection> source,
        IEnumerable<TItem> expected,
        [CallerArgumentExpression(nameof(expected))] string? expression = null)
        where TCollection : IEnumerable<TItem>
    {
        source.Context.ExpressionBuilder.Append($".IsNotEquivalentTo({expression})");
        return new NotEquivalentToAssertion<TCollection, TItem>(source.Context, expected);
    }

    /// <summary>
    /// Asserts that the collection is NOT equivalent to the expected collection using the specified comparer.
    /// </summary>
    public static NotEquivalentToAssertion<TCollection, TItem> IsNotEquivalentTo<TCollection, TItem>(
        this IAssertionSource<TCollection> source,
        IEnumerable<TItem> expected,
        IEqualityComparer<TItem> comparer,
        [CallerArgumentExpression(nameof(expected))] string? expression = null)
        where TCollection : IEnumerable<TItem>
    {
        source.Context.ExpressionBuilder.Append($".IsNotEquivalentTo({expression}, comparer)");
        return new NotEquivalentToAssertion<TCollection, TItem>(source.Context, expected).Using(comparer);
    }

    /// <summary>
    /// Asserts that the collection is NOT equivalent to the expected collection with the specified ordering requirement.
    /// </summary>
    public static NotEquivalentToAssertion<TCollection, TItem> IsNotEquivalentTo<TCollection, TItem>(
        this IAssertionSource<TCollection> source,
        IEnumerable<TItem> expected,
        Enums.CollectionOrdering ordering,
        [CallerArgumentExpression(nameof(expected))] string? expression = null)
        where TCollection : IEnumerable<TItem>
    {
        source.Context.ExpressionBuilder.Append($".IsNotEquivalentTo({expression}, CollectionOrdering.{ordering})");
        return new NotEquivalentToAssertion<TCollection, TItem>(source.Context, expected,  ordering);
    }

    /// <summary>
    /// Asserts that the value is NOT structurally equivalent to the expected value.
    /// Performs deep comparison of properties and fields.
    /// Supports .WithPartialEquivalency() and .IgnoringMember() for advanced scenarios.
    /// </summary>
    public static NotStructuralEquivalencyAssertion<TValue> IsNotEquivalentTo<TValue>(
        this IAssertionSource<TValue> source,
        object? expected,
        [CallerArgumentExpression(nameof(expected))] string? expression = null)
    {
        source.Context.ExpressionBuilder.Append($".IsNotEquivalentTo({expression})");
        return new NotStructuralEquivalencyAssertion<TValue>(source.Context, expected, expression);
    }

    // ============ PREDICATE CHECKS ============

    /// <summary>
    /// Asserts that the value satisfies the specified predicate.
    /// Example: await Assert.That(x).Satisfies(v => v > 0 && v < 100);
    /// </summary>
    public static SatisfiesAssertion<TValue> Satisfies<TValue>(
        this IAssertionSource<TValue> source,
        Func<TValue?, bool> predicate,
        [CallerArgumentExpression(nameof(predicate))] string? expression = null)
    {
        source.Context.ExpressionBuilder.Append($".Satisfies({expression})");
        return new SatisfiesAssertion<TValue>(source.Context, predicate, expression ?? "predicate");
    }

    /// <summary>
    /// Asserts that a mapped value satisfies custom assertions.
    /// Maps the source value using a selector, then runs assertions on the mapped value.
    /// Example: await Assert.That(model).Satisfies(m => m.Name, assert => assert.IsEqualTo("John"));
    /// </summary>
    public static MappedSatisfiesAssertion<TValue, TMapped> Satisfies<TValue, TMapped>(
        this IAssertionSource<TValue> source,
        Func<TValue?, TMapped> selector,
        Func<ValueAssertion<TMapped>, Assertion<TMapped>?> assertions,
        [CallerArgumentExpression(nameof(selector))] string? selectorExpression = null)
    {
        source.Context.ExpressionBuilder.Append($".Satisfies({selectorExpression}, ...)");
        return new MappedSatisfiesAssertion<TValue, TMapped>(
            source.Context,
            selector,
            assertions,
            selectorExpression ?? "selector");
    }

    /// <summary>
    /// Asserts that an async-mapped value satisfies custom assertions.
    /// Maps the source value using an async selector, then runs assertions on the mapped value.
    /// Example: await Assert.That(model).Satisfies(m => m.GetNameAsync(), assert => assert.IsEqualTo("John"));
    /// </summary>
    public static AsyncMappedSatisfiesAssertion<TValue, TMapped> Satisfies<TValue, TMapped>(
        this IAssertionSource<TValue> source,
        Func<TValue?, Task<TMapped>> selector,
        Func<ValueAssertion<TMapped>, Assertion<TMapped>?> assertions,
        [CallerArgumentExpression(nameof(selector))] string? selectorExpression = null)
    {
        source.Context.ExpressionBuilder.Append($".Satisfies({selectorExpression}, ...)");
        return new AsyncMappedSatisfiesAssertion<TValue, TMapped>(
            source.Context,
            selector,
            assertions,
            selectorExpression ?? "selector");
    }

    // IsEquatableOrEqualTo is now generated by AssertionExtensionGenerator

    // ============ MEMBERSHIP CHECKS ============
    // IsIn and IsNotIn with IEnumerable are now generated by AssertionExtensionGenerator
    // Params overloads remain as convenience methods

    /// <summary>
    /// Asserts that the value is in the specified collection (params array convenience method).
    /// Example: await Assert.That(5).IsIn(1, 3, 5, 7, 9);
    /// </summary>
    public static IsInAssertion<TValue> IsIn<TValue>(
        this IAssertionSource<TValue> source,
        params TValue[] collection)
    {
        source.Context.ExpressionBuilder.Append($".IsIn({string.Join(", ", collection)})");
        return new IsInAssertion<TValue>(source.Context, collection);
    }

    /// <summary>
    /// Asserts that the value is NOT in the specified collection (params array convenience method).
    /// Example: await Assert.That(4).IsNotIn(1, 3, 5, 7, 9);
    /// </summary>
    public static IsNotInAssertion<TValue> IsNotIn<TValue>(
        this IAssertionSource<TValue> source,
        params TValue[] collection)
    {
        source.Context.ExpressionBuilder.Append($".IsNotIn({string.Join(", ", collection)})");
        return new IsNotInAssertion<TValue>(source.Context, collection);
    }

    // ============ EXCEPTION CHECKS ============

    /// <summary>
    /// Asserts that the delegate throws the specified exception type (or subclass).
    /// Only available on delegate-based assertions for type safety.
    /// Example: await Assert.That(() => ThrowingMethod()).Throws&lt;InvalidOperationException&gt;();
    /// </summary>
    public static ThrowsAssertion<TException> Throws<TException, TValue>(
        this IDelegateAssertionSource<TValue> source)
        where TException : Exception
    {
        source.Context.ExpressionBuilder.Append($".Throws<{typeof(TException).Name}>()");
        // Use MapException to move exception from exception field to value field
        var mappedContext = source.Context.MapException<TException>();
        return new ThrowsAssertion<TException>(mappedContext);
    }

    /// <summary>
    /// Alias for Throws - asserts that the delegate throws the specified exception type.
    /// Only available on delegate-based assertions for type safety.
    /// Example: await Assert.That(() => ThrowingMethod()).ThrowsException&lt;InvalidOperationException&gt;();
    /// </summary>
    public static ThrowsAssertion<TException> ThrowsException<TException, TValue>(
        this IDelegateAssertionSource<TValue> source)
        where TException : Exception
    {
        source.Context.ExpressionBuilder.Append($".ThrowsException<{typeof(TException).Name}>()");
        var mappedContext = source.Context.MapException<TException>();
        return new ThrowsAssertion<TException>(mappedContext);
    }

    /// <summary>
    /// Asserts that the delegate throws any exception.
    /// Only available on delegate-based assertions for type safety.
    /// Example: await Assert.That(() => ThrowingMethod()).ThrowsException();
    /// </summary>
    public static ThrowsAssertion<Exception> ThrowsException<TValue>(
        this IDelegateAssertionSource<TValue> source)
    {
        source.Context.ExpressionBuilder.Append(".ThrowsException()");
        var mappedContext = source.Context.MapException<Exception>();
        return new ThrowsAssertion<Exception>(mappedContext);
    }

    /// <summary>
    /// Asserts that the async delegate throws the specified exception type (or subclass).
    /// Only available on delegate-based assertions for type safety.
    /// Example: await Assert.That(async () => await ThrowingMethodAsync()).ThrowsAsync&lt;InvalidOperationException&gt;();
    /// </summary>
    public static ThrowsAssertion<TException> ThrowsAsync<TValue, TException>(
        this IDelegateAssertionSource<TValue> source)
        where TException : Exception
    {
        source.Context.ExpressionBuilder.Append($".ThrowsAsync<{typeof(TException).Name}>()");
        var mappedContext = source.Context.MapException<TException>();
        return new ThrowsAssertion<TException>(mappedContext);
    }

    /// <summary>
    /// Asserts that the delegate throws exactly the specified exception type (not subclasses).
    /// Only available on delegate-based assertions for type safety.
    /// Example: await Assert.That(() => ThrowingMethod()).ThrowsExactly&lt;InvalidOperationException&gt;();
    /// </summary>
    public static ThrowsExactlyAssertion<TException> ThrowsExactly<TException, TValue>(
        this IDelegateAssertionSource<TValue> source)
        where TException : Exception
    {
        source.Context.ExpressionBuilder.Append($".ThrowsExactly<{typeof(TException).Name}>()");
        var mappedContext = source.Context.MapException<TException>();
        return new ThrowsExactlyAssertion<TException>(mappedContext);
    }

    /// <summary>
    /// Asserts that the delegate does not throw any exception and returns the actual value.
    /// Only available on delegate-based assertions for type safety.
    /// Example: await Assert.That(() => SafeMethod()).ThrowsNothing();
    /// </summary>
    public static ThrowsNothingAssertion<TValue> ThrowsNothing<TValue>(
        this IDelegateAssertionSource<TValue> source)
    {
        source.Context.ExpressionBuilder.Append(".ThrowsNothing()");
        // Preserve the value so it can be returned after the assertion
        return new ThrowsNothingAssertion<TValue>(source.Context);
    }

    // ============ EXCEPTION MESSAGE/PROPERTY ASSERTIONS ============
    // These work on IAssertionSource<TException> where the exception is the value

    /// <summary>
    /// Asserts that the exception message contains the specified substring.
    /// Works after Throws assertions.
    /// Example: await Assert.That(() => ThrowingMethod()).Throws&lt;Exception&gt;().WithMessageContaining("error");
    /// </summary>
    public static ExceptionMessageContainsAssertion<TException> WithMessageContaining<TException>(
        this IAssertionSource<TException> source,
        string expectedSubstring,
        [CallerArgumentExpression(nameof(expectedSubstring))] string? expression = null)
        where TException : Exception
    {
        source.Context.ExpressionBuilder.Append($".WithMessageContaining({expression})");
        return new ExceptionMessageContainsAssertion<TException>(source.Context, expectedSubstring);
    }

    /// <summary>
    /// Asserts that the exception message contains the specified substring using the specified comparison.
    /// Works after Throws assertions.
    /// Example: await Assert.That(() => ThrowingMethod()).Throws&lt;Exception&gt;().WithMessageContaining("error", StringComparison.OrdinalIgnoreCase);
    /// </summary>
    public static ExceptionMessageContainsAssertion<TException> WithMessageContaining<TException>(
        this IAssertionSource<TException> source,
        string expectedSubstring,
        StringComparison comparison,
        [CallerArgumentExpression(nameof(expectedSubstring))] string? expression = null)
        where TException : Exception
    {
        source.Context.ExpressionBuilder.Append($".WithMessageContaining({expression}, StringComparison.{comparison})");
        return new ExceptionMessageContainsAssertion<TException>(source.Context, expectedSubstring, comparison);
    }

    /// <summary>
    /// Alias for WithMessageContaining - asserts that the exception message contains the specified substring.
    /// Works after Throws assertions.
    /// Example: await Assert.That(() => ThrowingMethod()).Throws&lt;Exception&gt;().HasMessageContaining("error");
    /// </summary>
    public static ExceptionMessageContainsAssertion<TException> HasMessageContaining<TException>(
        this IAssertionSource<TException> source,
        string expectedSubstring,
        [CallerArgumentExpression(nameof(expectedSubstring))] string? expression = null)
        where TException : Exception
    {
        return source.WithMessageContaining(expectedSubstring, expression);
    }

    /// <summary>
    /// Alias for WithMessageContaining - asserts that the exception message contains the specified substring using the specified comparison.
    /// Works after Throws assertions.
    /// Example: await Assert.That(() => ThrowingMethod()).Throws&lt;Exception&gt;().HasMessageContaining("error", StringComparison.OrdinalIgnoreCase);
    /// </summary>
    public static ExceptionMessageContainsAssertion<TException> HasMessageContaining<TException>(
        this IAssertionSource<TException> source,
        string expectedSubstring,
        StringComparison comparison,
        [CallerArgumentExpression(nameof(expectedSubstring))] string? expression = null)
        where TException : Exception
    {
        return source.WithMessageContaining(expectedSubstring, comparison, expression);
    }

    /// <summary>
    /// Asserts that the exception message exactly equals the specified string.
    /// Works after Throws assertions.
    /// Example: await Assert.That(() => ThrowingMethod()).Throws&lt;Exception&gt;().WithMessage("exact message");
    /// </summary>
    public static ExceptionMessageEqualsAssertion<TException> WithMessage<TException>(
        this IAssertionSource<TException> source,
        string expectedMessage,
        [CallerArgumentExpression(nameof(expectedMessage))] string? expression = null)
        where TException : Exception
    {
        source.Context.ExpressionBuilder.Append($".WithMessage({expression})");
        return new ExceptionMessageEqualsAssertion<TException>(source.Context, expectedMessage);
    }

    /// <summary>
    /// Asserts that the exception message exactly equals the specified string using the specified comparison.
    /// Works after Throws assertions.
    /// Example: await Assert.That(() => ThrowingMethod()).Throws&lt;Exception&gt;().WithMessage("exact message", StringComparison.OrdinalIgnoreCase);
    /// </summary>
    public static ExceptionMessageEqualsAssertion<TException> WithMessage<TException>(
        this IAssertionSource<TException> source,
        string expectedMessage,
        StringComparison comparison,
        [CallerArgumentExpression(nameof(expectedMessage))] string? expression = null)
        where TException : Exception
    {
        source.Context.ExpressionBuilder.Append($".WithMessage({expression}, StringComparison.{comparison})");
        return new ExceptionMessageEqualsAssertion<TException>(source.Context, expectedMessage, comparison);
    }

    /// <summary>
    /// Asserts that the exception message does NOT contain the specified substring.
    /// Works after Throws assertions.
    /// Example: await Assert.That(() => ThrowingMethod()).Throws&lt;Exception&gt;().WithMessageNotContaining("should not appear");
    /// </summary>
    public static ExceptionMessageNotContainsAssertion<TException> WithMessageNotContaining<TException>(
        this IAssertionSource<TException> source,
        string notExpectedSubstring,
        [CallerArgumentExpression(nameof(notExpectedSubstring))] string? expression = null)
        where TException : Exception
    {
        source.Context.ExpressionBuilder.Append($".WithMessageNotContaining({expression})");
        return new ExceptionMessageNotContainsAssertion<TException>(source.Context, notExpectedSubstring);
    }

    /// <summary>
    /// Asserts that the exception message does NOT contain the specified substring using the specified comparison.
    /// Works after Throws assertions.
    /// Example: await Assert.That(() => ThrowingMethod()).Throws&lt;Exception&gt;().WithMessageNotContaining("should not appear", StringComparison.OrdinalIgnoreCase);
    /// </summary>
    public static ExceptionMessageNotContainsAssertion<TException> WithMessageNotContaining<TException>(
        this IAssertionSource<TException> source,
        string notExpectedSubstring,
        StringComparison comparison,
        [CallerArgumentExpression(nameof(notExpectedSubstring))] string? expression = null)
        where TException : Exception
    {
        source.Context.ExpressionBuilder.Append($".WithMessageNotContaining({expression}, StringComparison.{comparison})");
        return new ExceptionMessageNotContainsAssertion<TException>(source.Context, notExpectedSubstring, comparison);
    }

    /// <summary>
    /// Asserts that the exception message matches a wildcard pattern.
    /// * matches any number of characters, ? matches a single character.
    /// Works after Throws assertions.
    /// Example: await Assert.That(() => ThrowingMethod()).Throws&lt;Exception&gt;().WithMessageMatching("Error: *");
    /// </summary>
    public static ExceptionMessageMatchesPatternAssertion<TException> WithMessageMatching<TException>(
        this IAssertionSource<TException> source,
        string pattern,
        [CallerArgumentExpression(nameof(pattern))] string? expression = null)
        where TException : Exception
    {
        source.Context.ExpressionBuilder.Append($".WithMessageMatching({expression})");
        return new ExceptionMessageMatchesPatternAssertion<TException>(source.Context, pattern);
    }

    /// <summary>
    /// Asserts that the exception message matches a StringMatcher pattern.
    /// Works after Throws assertions.
    /// Example: await Assert.That(() => ThrowingMethod()).Throws&lt;Exception&gt;().WithMessageMatching(StringMatcher.Regex("Error.*"));
    /// </summary>
    public static ExceptionMessageMatchesAssertion<TException> WithMessageMatching<TException>(
        this IAssertionSource<TException> source,
        StringMatcher matcher,
        [CallerArgumentExpression(nameof(matcher))] string? expression = null)
        where TException : Exception
    {
        source.Context.ExpressionBuilder.Append($".WithMessageMatching({expression})");
        return new ExceptionMessageMatchesAssertion<TException>(source.Context, matcher);
    }

    /// <summary>
    /// Asserts that an ArgumentException has the specified parameter name.
    /// Works after Throws assertions.
    /// Example: await Assert.That(() => ThrowingMethod()).Throws&lt;ArgumentException&gt;().WithParameterName("paramName");
    /// </summary>
    public static ExceptionParameterNameAssertion<TException> WithParameterName<TException>(
        this IAssertionSource<TException> source,
        string expectedParameterName,
        [CallerArgumentExpression(nameof(expectedParameterName))] string? expression = null)
        where TException : Exception
    {
        source.Context.ExpressionBuilder.Append($".WithParameterName({expression})");
        return new ExceptionParameterNameAssertion<TException>(source.Context, expectedParameterName);
    }

    // Specific overloads for delegate types where TValue is always object?
    public static ThrowsAssertion<TException> Throws<TException>(this DelegateAssertion source) where TException : Exception
    {
        var iface = (IAssertionSource<object?>)source;
        iface.Context.ExpressionBuilder.Append($".Throws<{typeof(TException).Name}>()");
        var mappedContext = iface.Context.MapException<TException>();
        return new ThrowsAssertion<TException>(mappedContext);
    }

    public static ThrowsExactlyAssertion<TException> ThrowsExactly<TException>(this DelegateAssertion source) where TException : Exception
    {
        var iface = (IAssertionSource<object?>)source;
        iface.Context.ExpressionBuilder.Append($".ThrowsExactly<{typeof(TException).Name}>()");
        var mappedContext = iface.Context.MapException<TException>();
        return new ThrowsExactlyAssertion<TException>(mappedContext);
    }

    public static ThrowsAssertion<TException> Throws<TException>(this AsyncDelegateAssertion source) where TException : Exception
    {
        var iface = (IAssertionSource<object?>)source;
        iface.Context.ExpressionBuilder.Append($".Throws<{typeof(TException).Name}>()");
        var mappedContext = iface.Context.MapException<TException>();
        return new ThrowsAssertion<TException>(mappedContext);
    }

    public static ThrowsExactlyAssertion<TException> ThrowsExactly<TException>(this AsyncDelegateAssertion source) where TException : Exception
    {
        var iface = (IAssertionSource<object?>)source;
        iface.Context.ExpressionBuilder.Append($".ThrowsExactly<{typeof(TException).Name}>()");
        var mappedContext = iface.Context.MapException<TException>();
        return new ThrowsExactlyAssertion<TException>(mappedContext);
    }

    /// <summary>
    /// Asserts that an exception's Message property exactly equals the expected string.
    /// Works with both direct exception assertions and chained exception assertions (via .And).
    /// </summary>
    public static HasMessageEqualToAssertion<TValue> HasMessageEqualTo<TValue>(
        this IAssertionSource<TValue> source,
        string expectedMessage)
    {
        source.Context.ExpressionBuilder.Append($".HasMessageEqualTo(\"{expectedMessage}\")");
        return new HasMessageEqualToAssertion<TValue>(source.Context, expectedMessage);
    }

    /// <summary>
    /// Asserts that an exception's Message property exactly equals the expected string using the specified string comparison.
    /// Works with both direct exception assertions and chained exception assertions (via .And).
    /// </summary>
    public static HasMessageEqualToAssertion<TValue> HasMessageEqualTo<TValue>(
        this IAssertionSource<TValue> source,
        string expectedMessage,
        StringComparison comparison)
    {
        source.Context.ExpressionBuilder.Append($".HasMessageEqualTo(\"{expectedMessage}\", StringComparison.{comparison})");
        return new HasMessageEqualToAssertion<TValue>(source.Context, expectedMessage,  comparison);
    }


    /// <summary>
    /// Asserts that an exception's Message property starts with the expected string.
    /// Works with both direct exception assertions and chained exception assertions (via .And).
    /// </summary>
    public static HasMessageStartingWithAssertion<TValue> HasMessageStartingWith<TValue>(
        this IAssertionSource<TValue> source,
        string expectedPrefix)
    {
        source.Context.ExpressionBuilder.Append($".HasMessageStartingWith(\"{expectedPrefix}\")");
        return new HasMessageStartingWithAssertion<TValue>(source.Context, expectedPrefix);
    }

    /// <summary>
    /// Asserts that an exception's Message property starts with the expected string using the specified string comparison.
    /// Works with both direct exception assertions and chained exception assertions (via .And).
    /// </summary>
    public static HasMessageStartingWithAssertion<TValue> HasMessageStartingWith<TValue>(
        this IAssertionSource<TValue> source,
        string expectedPrefix,
        StringComparison comparison)
    {
        source.Context.ExpressionBuilder.Append($".HasMessageStartingWith(\"{expectedPrefix}\", StringComparison.{comparison})");
        return new HasMessageStartingWithAssertion<TValue>(source.Context, expectedPrefix,  comparison);
    }


    /// <summary>
    /// Asserts that the DateTime is after or equal to the expected DateTime.
    /// Alias for IsGreaterThanOrEqualTo for better readability with dates.
    /// </summary>
    public static GreaterThanOrEqualAssertion<DateTime> IsAfterOrEqualTo(
        this IAssertionSource<DateTime> source,
        DateTime expected,
        [CallerArgumentExpression(nameof(expected))] string? expression = null)
    {
        source.Context.ExpressionBuilder.Append($".IsAfterOrEqualTo({expression})");
        return new GreaterThanOrEqualAssertion<DateTime>(source.Context, expected);
    }

    // IsDefault and IsNotDefault are now generated by AssertionExtensionGenerator

    // ============ TIMING ASSERTIONS ============

    /// <summary>
    /// Asserts that a synchronous delegate completes execution within the specified timeout.
    /// If the delegate takes longer than the timeout, the assertion fails.
    /// </summary>
    public static CompletesWithinActionAssertion CompletesWithin(
        this DelegateAssertion source,
        TimeSpan timeout,
        [CallerArgumentExpression(nameof(timeout))] string? expression = null)
    {
        var action = GetActionFromDelegate(source);
        var assertionSource = (IAssertionSource<object?>)source;
        assertionSource.Context.ExpressionBuilder.Append($".CompletesWithin({expression})");
        return new CompletesWithinActionAssertion(action, timeout);
    }

    /// <summary>
    /// Asserts that an asynchronous delegate completes execution within the specified timeout.
    /// If the delegate takes longer than the timeout, the assertion fails.
    /// </summary>
    public static CompletesWithinAsyncAssertion CompletesWithin(
        this AsyncDelegateAssertion source,
        TimeSpan timeout,
        [CallerArgumentExpression(nameof(timeout))] string? expression = null)
    {
        var asyncAction = GetFuncFromAsyncDelegate(source);
        var assertionSource = (IAssertionSource<object?>)source;
        assertionSource.Context.ExpressionBuilder.Append($".CompletesWithin({expression})");
        return new CompletesWithinAsyncAssertion(asyncAction, timeout);
    }

    private static Action GetActionFromDelegate(DelegateAssertion source)
    {
        return source.Action;
    }

    private static Func<Task> GetFuncFromAsyncDelegate(AsyncDelegateAssertion source)
    {
        return source.AsyncAction;
    }

    // ============ PARSING ASSERTIONS ============

    /// <summary>
    /// Asserts that a string can be parsed into the specified type.
    /// </summary>
    public static Assertions.Strings.IsParsableIntoAssertion<T> IsParsableInto<[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicMethods | DynamicallyAccessedMemberTypes.Interfaces)] T>(
        this IAssertionSource<string> source)
    {
        source.Context.ExpressionBuilder.Append($".IsParsableInto<{typeof(T).Name}>()");
        return new Assertions.Strings.IsParsableIntoAssertion<T>(source.Context);
    }

    /// <summary>
    /// Asserts that a string cannot be parsed into the specified type.
    /// </summary>
    public static Assertions.Strings.IsNotParsableIntoAssertion<T> IsNotParsableInto<[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicMethods | DynamicallyAccessedMemberTypes.Interfaces)] T>(
        this IAssertionSource<string> source)
    {
        source.Context.ExpressionBuilder.Append($".IsNotParsableInto<{typeof(T).Name}>()");
        return new Assertions.Strings.IsNotParsableIntoAssertion<T>(source.Context);
    }

    /// <summary>
    /// Parses a string into the specified type and returns an assertion on the parsed value.
    /// This allows chaining assertions on the parsed result.
    /// </summary>
    public static Assertions.Strings.WhenParsedIntoAssertion<T> WhenParsedInto<[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicMethods | DynamicallyAccessedMemberTypes.Interfaces)] T>(
        this IAssertionSource<string> source)
    {
        source.Context.ExpressionBuilder.Append($".WhenParsedInto<{typeof(T).Name}>()");
        return new Assertions.Strings.WhenParsedIntoAssertion<T>(source.Context);
    }

    // ============ ENUM ASSERTIONS ============

    /// <summary>
    /// Asserts that a flags enum has the specified flag set.
    /// </summary>
    public static Assertions.Enums.HasFlagAssertion<TEnum> HasFlag<TEnum>(
        this IAssertionSource<TEnum> source,
        TEnum expectedFlag,
        [CallerArgumentExpression(nameof(expectedFlag))] string? expression = null)
        where TEnum : struct, Enum
    {
        source.Context.ExpressionBuilder.Append($".HasFlag({expression})");
        return new Assertions.Enums.HasFlagAssertion<TEnum>(source.Context, expectedFlag);
    }

    /// <summary>
    /// Asserts that a flags enum does NOT have the specified flag set.
    /// </summary>
    public static Assertions.Enums.DoesNotHaveFlagAssertion<TEnum> DoesNotHaveFlag<TEnum>(
        this IAssertionSource<TEnum> source,
        TEnum unexpectedFlag,
        [CallerArgumentExpression(nameof(unexpectedFlag))] string? expression = null)
        where TEnum : struct, Enum
    {
        source.Context.ExpressionBuilder.Append($".DoesNotHaveFlag({expression})");
        return new Assertions.Enums.DoesNotHaveFlagAssertion<TEnum>(source.Context, unexpectedFlag);
    }

    /// <summary>
    /// Asserts that an enum value is defined in its enum type.
    /// </summary>
    public static Assertions.Enums.IsDefinedAssertion<TEnum> IsDefined<TEnum>(
        this IAssertionSource<TEnum> source)
        where TEnum : struct, Enum
    {
        source.Context.ExpressionBuilder.Append(".IsDefined()");
        return new Assertions.Enums.IsDefinedAssertion<TEnum>(source.Context);
    }

    /// <summary>
    /// Asserts that an enum value is NOT defined in its enum type.
    /// </summary>
    public static Assertions.Enums.IsNotDefinedAssertion<TEnum> IsNotDefined<TEnum>(
        this IAssertionSource<TEnum> source)
        where TEnum : struct, Enum
    {
        source.Context.ExpressionBuilder.Append(".IsNotDefined()");
        return new Assertions.Enums.IsNotDefinedAssertion<TEnum>(source.Context);
    }

    /// <summary>
    /// Asserts that two enum values have the same name.
    /// </summary>
    public static Assertions.Enums.HasSameNameAsAssertion<TEnum> HasSameNameAs<TEnum>(
        this IAssertionSource<TEnum> source,
        Enum otherEnumValue,
        [CallerArgumentExpression(nameof(otherEnumValue))] string? expression = null)
        where TEnum : struct, Enum
    {
        source.Context.ExpressionBuilder.Append($".HasSameNameAs({expression})");
        return new Assertions.Enums.HasSameNameAsAssertion<TEnum>(source.Context, otherEnumValue);
    }

    /// <summary>
    /// Asserts that two enum values have the same underlying value.
    /// </summary>
    public static Assertions.Enums.HasSameValueAsAssertion<TEnum> HasSameValueAs<TEnum>(
        this IAssertionSource<TEnum> source,
        Enum otherEnumValue,
        [CallerArgumentExpression(nameof(otherEnumValue))] string? expression = null)
        where TEnum : struct, Enum
    {
        source.Context.ExpressionBuilder.Append($".HasSameValueAs({expression})");
        return new Assertions.Enums.HasSameValueAsAssertion<TEnum>(source.Context, otherEnumValue);
    }

    /// <summary>
    /// Asserts that two enum values do NOT have the same name.
    /// </summary>
    public static Assertions.Enums.DoesNotHaveSameNameAsAssertion<TEnum> DoesNotHaveSameNameAs<TEnum>(
        this IAssertionSource<TEnum> source,
        Enum otherEnumValue,
        [CallerArgumentExpression(nameof(otherEnumValue))] string? expression = null)
        where TEnum : struct, Enum
    {
        source.Context.ExpressionBuilder.Append($".DoesNotHaveSameNameAs({expression})");
        return new Assertions.Enums.DoesNotHaveSameNameAsAssertion<TEnum>(source.Context, otherEnumValue);
    }

    /// <summary>
    /// Asserts that two enum values do NOT have the same underlying value.
    /// </summary>
    public static Assertions.Enums.DoesNotHaveSameValueAsAssertion<TEnum> DoesNotHaveSameValueAs<TEnum>(
        this IAssertionSource<TEnum> source,
        Enum otherEnumValue,
        [CallerArgumentExpression(nameof(otherEnumValue))] string? expression = null)
        where TEnum : struct, Enum
    {
        source.Context.ExpressionBuilder.Append($".DoesNotHaveSameValueAs({expression})");
        return new Assertions.Enums.DoesNotHaveSameValueAsAssertion<TEnum>(source.Context, otherEnumValue);
    }

    /// <summary>
    /// Asserts that a value's type is assignable to a specific type (specialized for object).
    /// Manual extension - should be auto-generated when generator works.
    /// </summary>
    public static IsAssignableToAssertion<TTarget, object> IsAssignableTo<TTarget>(
        this IAssertionSource<object> source)
    {
        source.Context.ExpressionBuilder.Append($".IsAssignableTo<{typeof(TTarget).Name}>()");
        return new IsAssignableToAssertion<TTarget, object>(source.Context);
    }

    /// <summary>
    /// Asserts that a value's type is assignable to a specific type.
    /// Manual extension - should be auto-generated when generator works.
    /// </summary>
    public static IsAssignableToAssertion<TTarget, TValue> IsAssignableTo<TTarget, TValue>(
        this IAssertionSource<TValue> source)
    {
        source.Context.ExpressionBuilder.Append($".IsAssignableTo<{typeof(TTarget).Name}>()");
        return new IsAssignableToAssertion<TTarget, TValue>(source.Context);
    }

    /// <summary>
    /// Asserts that a value's type is NOT assignable to a specific type.
    /// Manual extension - should be auto-generated when generator works.
    /// </summary>
    public static IsNotAssignableToAssertion<TTarget, TValue> IsNotAssignableTo<TTarget, TValue>(
        this IAssertionSource<TValue> source)
    {
        source.Context.ExpressionBuilder.Append($".IsNotAssignableTo<{typeof(TTarget).Name}>()");
        return new IsNotAssignableToAssertion<TTarget, TValue>(source.Context);
    }
}
