import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docs: [
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: [
        'intro',
        'getting-started/installation',
        'getting-started/writing-your-first-test',
        'getting-started/running-your-tests',
      ],
    },
    {
      type: 'category',
      label: 'Writing Tests',
      collapsed: true,
      items: [
        'writing-tests/things-to-know',
        {
          type: 'category',
          label: 'Lifecycle & Hooks',
          collapsed: true,
          items: [
            'writing-tests/lifecycle',
            'writing-tests/hooks-setup',
            'writing-tests/hooks-cleanup',
            'writing-tests/test-context',
            'writing-tests/artifacts',
            'writing-tests/property-injection',
            'writing-tests/dependency-injection',
            'writing-tests/event-subscribing',
          ],
        },
        {
          type: 'category',
          label: 'Test Data',
          collapsed: true,
          items: [
            'writing-tests/arguments',
            'writing-tests/method-data-source',
            'writing-tests/class-data-source',
            'writing-tests/test-data-row',
            'writing-tests/matrix-tests',
            'writing-tests/combined-data-source',
            'writing-tests/nested-data-sources',
            'writing-tests/generic-attributes',
          ],
        },
        {
          type: 'category',
          label: 'Controlling Execution',
          collapsed: true,
          items: [
            'writing-tests/skip',
            'writing-tests/explicit',
            'writing-tests/ordering',
            'writing-tests/culture',
            'writing-tests/aot',
          ],
        },
        {
          type: 'category',
          label: 'Mocking',
          collapsed: true,
          items: [
            'writing-tests/mocking/index',
            'writing-tests/mocking/setup',
            'writing-tests/mocking/verification',
            'writing-tests/mocking/argument-matchers',
            'writing-tests/mocking/advanced',
            'writing-tests/mocking/http',
            'writing-tests/mocking/logging',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Assertions',
      collapsed: true,
      items: [
        'assertions/getting-started',
        'assertions/awaiting',
        {
          type: 'category',
          label: 'Value Assertions',
          collapsed: true,
          items: [
            'assertions/equality-and-comparison',
            'assertions/null-and-default',
            'assertions/boolean',
            'assertions/numeric',
            'assertions/string',
            'assertions/datetime',
            'assertions/types',
            'assertions/specialized-types',
          ],
        },
        {
          type: 'category',
          label: 'Collections',
          collapsed: true,
          items: [
            'assertions/collections',
            'assertions/dictionaries',
          ],
        },
        {
          type: 'category',
          label: 'Async & Exceptions',
          collapsed: true,
          items: [
            'assertions/tasks-and-async',
            'assertions/exceptions',
            'assertions/delegates',
          ],
        },
        'assertions/combining-assertions',
        'assertions/member-assertions',
        'assertions/regex-assertions',
        'assertions/type-checking',
        'assertions/fsharp',
        {
          type: 'category',
          label: 'Custom Assertions',
          collapsed: true,
          items: [
            'assertions/extensibility/custom-assertions',
            'assertions/extensibility/source-generator-assertions',
            'assertions/extensibility/extensibility-chaining-and-converting',
            'assertions/extensibility/extensibility-returning-items-from-await',
          ],
        },
        'assertions/library',
      ],
    },
    {
      type: 'category',
      label: 'Running Tests',
      collapsed: true,
      items: [
        'execution/test-filters',
        'execution/timeouts',
        'execution/retrying',
        'execution/repeating',
        'execution/parallelism',
        'execution/ci-cd-reporting',
        'execution/engine-modes',
      ],
    },
    {
      type: 'category',
      label: 'Extending TUnit',
      collapsed: true,
      items: [
        'extending/extension-points',
        'extending/data-source-generators',
        'extending/argument-formatters',
        'extending/display-names',
        'extending/logging',
        'extending/exception-handling',
        'extending/test-variants',
        'extending/dynamic-tests',
        'extending/built-in-extensions',
        'extending/code-coverage',
        'extending/libraries',
      ],
    },
    {
      type: 'category',
      label: 'Migration Guides',
      collapsed: true,
      items: [
        'comparison/framework-differences',
        'comparison/attributes',
        'migration/xunit',
        'migration/nunit',
        'migration/mstest',
        'migration/testcontext-interface-organization',
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      collapsed: true,
      items: [
        'guides/best-practices',
        'guides/performance',
        'guides/cookbook',
        'examples/aspnet',
        'examples/aspire',
        'examples/playwright',
        'examples/complex-test-infrastructure',
        'examples/fscheck',
        'examples/opentelemetry',
        'examples/filebased-csharp',
        'examples/fsharp-interactive',
        'examples/tunit-ci-pipeline',
        'examples/instrumenting-global-test-ids',
      ],
    },
    'troubleshooting',
    {
      type: 'category',
      label: 'Reference',
      collapsed: true,
      items: [
        'reference/command-line-flags',
        'reference/environment-variables',
        'reference/test-configuration',
      ],
    },
    {
      type: 'category',
      label: 'About TUnit',
      collapsed: true,
      items: [
        'guides/philosophy',
        {
          type: 'category',
          label: 'Benchmarks',
          collapsed: true,
          items: [
            {
              type: 'autogenerated',
              dirName: 'benchmarks',
            },
          ],
        },
      ],
    },
  ],
};

export default sidebars;
